//! `GET /api/attachments/{session_id}/{filename}` — serve session-scoped
//! attachment files to remote clients.
//!
//! Access is gated by the usual API-key middleware; here we add path-level
//! safety: session-id whitelist, filename denylist, canonicalized path
//! containment (all via [`super::file_serve`]), plus a sniffed
//! `Content-Type` / `Content-Disposition` so browsers pick inline vs
//! download correctly. Range requests are handled by
//! `tower_http::services::ServeFile` so large media streams correctly.
//!
//! The `_temp` pseudo-session maps to `~/.hope-agent/attachments/_temp/`
//! so pre-session uploads remain reachable until promoted to a real session.

use std::path::PathBuf;

use axum::extract::{Path, Query, Request};
use axum::response::{IntoResponse, Response};
use serde::Deserialize;
use tower::ServiceExt;
use tower_http::services::ServeFile;

use ha_core::attachments::TEMP_SESSION_ID;
use ha_core::paths;

use crate::error::AppError;
use crate::routes::file_serve::{
    apply_inline_media_headers, contained_canonical, resolve_mime_for_path, validate_safe_filename,
    HeaderOpts, MimeOpts,
};

#[derive(Debug, Deserialize)]
pub struct AttachmentDownloadQuery {
    pub download: Option<String>,
}

/// `GET /api/attachments/{session_id}/{filename}` — binary file download.
pub async fn download(
    Path((session_id, filename)): Path<(String, String)>,
    Query(q): Query<AttachmentDownloadQuery>,
    request: Request,
) -> Result<Response, AppError> {
    validate_session_id(&session_id)?;
    validate_safe_filename(&filename)?;

    let base_dir = resolve_base_dir(&session_id)?;
    let candidate = base_dir.join(&filename);
    let file_canon = contained_canonical(&base_dir, &candidate).await?;

    // MIME sniff fallback is needed here because users upload arbitrary
    // file types (ext-less, mis-named `.bin`, etc.).
    let mime = resolve_mime_for_path(
        &file_canon,
        MimeOpts {
            html_charset: false,
            sniff_fallback: true,
        },
    )
    .await;

    let force_download = q.download.as_deref().map(str::trim).is_some_and(|v| {
        v == "1" || v.eq_ignore_ascii_case("true") || v.eq_ignore_ascii_case("yes")
    });
    let disposition_kind = if force_download {
        "attachment"
    } else if mime.starts_with("image/")
        || mime.starts_with("video/")
        || mime.starts_with("audio/")
        || mime == "application/pdf"
    {
        "inline"
    } else {
        "attachment"
    };
    let quoted = filename.replace('\\', "\\\\").replace('"', "\\\"");
    let disposition = format!("{}; filename=\"{}\"", disposition_kind, quoted);

    let mut response = ServeFile::new(&file_canon)
        .oneshot(request)
        .await
        .map_err(|e| AppError::internal(format!("serve attachment: {}", e)))?
        .into_response();

    apply_inline_media_headers(
        &mut response,
        HeaderOpts {
            mime: &mime,
            cache_secs: 300,
            disposition: &disposition,
            no_referrer: false,
        },
    );

    Ok(response)
}

fn resolve_base_dir(session_id: &str) -> Result<PathBuf, AppError> {
    if session_id == TEMP_SESSION_ID {
        let root = paths::root_dir().map_err(|e| AppError::internal(e.to_string()))?;
        Ok(root.join("attachments").join(TEMP_SESSION_ID))
    } else {
        paths::attachments_dir(session_id).map_err(|e| AppError::internal(e.to_string()))
    }
}

/// Session IDs are either UUIDs / short slugs generated by `SessionDB` or the
/// literal `_temp`. Reject anything that could escape the attachments root.
fn validate_session_id(sid: &str) -> Result<(), AppError> {
    if sid == TEMP_SESSION_ID {
        return Ok(());
    }
    if sid.is_empty() || sid.len() > 128 {
        return Err(AppError::bad_request("invalid session id"));
    }
    if !sid
        .bytes()
        .all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_')
    {
        return Err(AppError::bad_request("invalid session id"));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn session_id_accepts_typical_ids() {
        assert!(validate_session_id("abc123").is_ok());
        assert!(validate_session_id("ABC-def_012").is_ok());
        assert!(validate_session_id("_temp").is_ok());
    }

    #[test]
    fn session_id_rejects_traversal_and_empty() {
        assert!(validate_session_id("").is_err());
        assert!(validate_session_id("..").is_err());
        assert!(validate_session_id("a/b").is_err());
        assert!(validate_session_id("a\\b").is_err());
        assert!(validate_session_id(".dotfile").is_err());
    }
}
