import type { ProviderTemplate } from "../types"

export const chinaTemplates: ProviderTemplate[] = [
  // ── 国内 Provider ──
  {
    key: "moonshot",
    name: "Moonshot AI (Kimi)",
    description: "Kimi 系列长上下文模型",
    icon: "🌙",
    apiType: "openai-chat",
    baseUrl: "https://api.moonshot.ai/v1",
    apiKeyPlaceholder: "sk-...",
    requiresApiKey: true,
    models: [
      {
        id: "kimi-k3",
        name: "Kimi K3",
        inputTypes: ["text", "image"],
        contextWindow: 1048576,
        maxTokens: 1048576,
        reasoning: true,
        costInput: 3.0,
        costOutput: 15.0,
      },
      {
        id: "kimi-k2.7-code",
        name: "Kimi K2.7 Code",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: true,
        costInput: 0.95,
        costOutput: 4.0,
      },
      {
        id: "kimi-k2.6",
        name: "Kimi K2.6",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: false,
        costInput: 0.95,
        costOutput: 4.0,
      },
      {
        id: "kimi-k2.5",
        name: "Kimi K2.5",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: false,
        costInput: 0.6,
        costOutput: 3.0,
      },
      {
        id: "kimi-k2-thinking",
        name: "Kimi K2 Thinking",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "kimi-k2-thinking-turbo",
        name: "Kimi K2 Thinking Turbo",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "kimi-k2-turbo",
        name: "Kimi K2 Turbo",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "qwen",
    name: "通义千问 (Qwen)",
    description: "阿里云 DashScope 大模型",
    icon: "☁️",
    apiType: "openai-chat",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode",
    apiKeyPlaceholder: "sk-...",
    requiresApiKey: true,
    models: [
      {
        id: "qwen-max",
        name: "Qwen Max",
        inputTypes: ["text"],
        contextWindow: 32768,
        maxTokens: 8192,
        reasoning: false,
        costInput: 2.4,
        costOutput: 9.6,
      },
      {
        id: "qwen-plus",
        name: "Qwen Plus",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.8,
        costOutput: 2.0,
      },
      {
        id: "qwen-turbo",
        name: "Qwen Turbo",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.3,
        costOutput: 0.6,
      },
      {
        id: "qwq-plus",
        name: "QwQ Plus (推理)",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 16384,
        reasoning: true,
        costInput: 1.6,
        costOutput: 4.0,
      },
    ],
    thinkingStyle: "qwen",
  },
  {
    key: "volcengine",
    name: "火山引擎 (豆包)",
    description: "字节跳动 Doubao 系列模型",
    icon: "🌋",
    apiType: "openai-chat",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "doubao-seed-code-preview-251028",
        name: "Doubao Seed Code",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0.0001,
        costOutput: 0.0002,
      },
      {
        id: "doubao-seed-1-8-251228",
        name: "Doubao Seed 1.8",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0.0001,
        costOutput: 0.0002,
      },
      {
        id: "kimi-k2-5-260127",
        name: "Kimi K2.5",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0.0001,
        costOutput: 0.0002,
      },
      {
        id: "glm-4-7-251222",
        name: "GLM 4.7",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0.0001,
        costOutput: 0.0002,
      },
      {
        id: "deepseek-v3-2-251201",
        name: "DeepSeek V3.2",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0.0001,
        costOutput: 0.0002,
      },
    ],
  },
  {
    key: "zhipu",
    name: "智谱 AI (Z.AI)",
    description: "GLM 系列模型",
    icon: "🧠",
    apiType: "openai-chat",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "glm-5.2",
        name: "GLM-5.2",
        inputTypes: ["text"],
        contextWindow: 1000000,
        maxTokens: 131072,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "glm-5.1",
        name: "GLM-5.1",
        inputTypes: ["text"],
        contextWindow: 202800,
        maxTokens: 131100,
        reasoning: true,
        costInput: 1.2,
        costOutput: 4.0,
      },
      {
        id: "glm-5",
        name: "GLM-5",
        inputTypes: ["text"],
        contextWindow: 202800,
        maxTokens: 131100,
        reasoning: true,
        costInput: 1.0,
        costOutput: 3.2,
      },
      {
        id: "glm-5-turbo",
        name: "GLM-5 Turbo",
        inputTypes: ["text"],
        contextWindow: 202800,
        maxTokens: 131100,
        reasoning: true,
        costInput: 1.2,
        costOutput: 4.0,
      },
      {
        id: "glm-5v-turbo",
        name: "GLM-5V Turbo",
        inputTypes: ["text", "image"],
        contextWindow: 202800,
        maxTokens: 131100,
        reasoning: true,
        costInput: 1.2,
        costOutput: 4.0,
      },
      {
        id: "glm-4.7",
        name: "GLM-4.7",
        inputTypes: ["text"],
        contextWindow: 204800,
        maxTokens: 131072,
        reasoning: true,
        costInput: 0.6,
        costOutput: 2.2,
      },
      {
        id: "glm-4.7-flash",
        name: "GLM-4.7 Flash",
        inputTypes: ["text"],
        contextWindow: 200000,
        maxTokens: 131072,
        reasoning: true,
        costInput: 0.07,
        costOutput: 0.4,
      },
      {
        id: "glm-4.7-flashx",
        name: "GLM-4.7 FlashX",
        inputTypes: ["text"],
        contextWindow: 200000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 0.06,
        costOutput: 0.4,
      },
      {
        id: "glm-4.6",
        name: "GLM-4.6",
        inputTypes: ["text"],
        contextWindow: 204800,
        maxTokens: 131072,
        reasoning: true,
        costInput: 0.6,
        costOutput: 2.2,
      },
      {
        id: "glm-4.6v",
        name: "GLM-4.6V",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 32768,
        reasoning: true,
        costInput: 0.3,
        costOutput: 0.9,
      },
      {
        id: "glm-4.5",
        name: "GLM-4.5",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 98304,
        reasoning: true,
        costInput: 0.6,
        costOutput: 2.2,
      },
      {
        id: "glm-4.5-air",
        name: "GLM-4.5 Air",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 98304,
        reasoning: true,
        costInput: 0.2,
        costOutput: 1.1,
      },
      {
        id: "glm-4.5-flash",
        name: "GLM-4.5 Flash",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 98304,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "glm-4.5v",
        name: "GLM-4.5V",
        inputTypes: ["text", "image"],
        contextWindow: 64000,
        maxTokens: 16384,
        reasoning: true,
        costInput: 0.6,
        costOutput: 1.8,
      },
    ],
    thinkingStyle: "zai",
  },
  {
    key: "minimax",
    name: "MiniMax",
    description: "MiniMax M2 系列模型 (Anthropic 兼容)",
    icon: "🔶",
    apiType: "anthropic",
    baseUrl: "https://api.minimax.io/anthropic",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "MiniMax-M3",
        name: "MiniMax M3",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 131072,
        reasoning: true,
        costInput: 0.6,
        costOutput: 2.4,
      },
      {
        id: "MiniMax-M2.7",
        name: "MiniMax M2.7",
        inputTypes: ["text"],
        contextWindow: 204800,
        maxTokens: 131072,
        reasoning: true,
        costInput: 0.3,
        costOutput: 1.2,
      },
      {
        id: "MiniMax-M2.7-highspeed",
        name: "MiniMax M2.7 Highspeed",
        inputTypes: ["text"],
        contextWindow: 204800,
        maxTokens: 131072,
        reasoning: true,
        costInput: 0.6,
        costOutput: 2.4,
      },
      {
        id: "MiniMax-M2.5",
        name: "MiniMax M2.5",
        inputTypes: ["text"],
        contextWindow: 200000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0.3,
        costOutput: 1.2,
      },
      {
        id: "MiniMax-VL-01",
        name: "MiniMax VL 01",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.3,
        costOutput: 1.2,
      },
    ],
    thinkingStyle: "anthropic",
  },
  {
    key: "kimi-coding",
    name: "Kimi Coding",
    description: "Kimi for Coding (Anthropic 兼容)",
    icon: "🌑",
    apiType: "anthropic",
    baseUrl: "https://api.kimi.com/coding/",
    apiKeyPlaceholder: "sk-...",
    requiresApiKey: true,
    models: [
      {
        id: "kimi-for-coding",
        name: "Kimi Code",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 32768,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "k3",
        name: "Kimi K3",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 32768,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "k3[1m]",
        name: "Kimi K3 (1M)",
        inputTypes: ["text", "image"],
        contextWindow: 1048576,
        maxTokens: 32768,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "kimi-code",
        name: "Kimi Code (legacy kimi-code)",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 32768,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "k2p5",
        name: "Kimi Code (legacy k2p5)",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 32768,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
    ],
    thinkingStyle: "anthropic",
  },
  {
    key: "xiaomi",
    name: "小米 MiMo",
    description: "MiMo 系列模型",
    icon: "📱",
    apiType: "openai-chat",
    baseUrl: "https://api.xiaomimimo.com/v1",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "mimo-v2-pro",
        name: "Xiaomi MiMo V2 Pro",
        inputTypes: ["text"],
        contextWindow: 1048576,
        maxTokens: 32000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "mimo-v2-omni",
        name: "Xiaomi MiMo V2 Omni",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 32000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "mimo-v2-flash",
        name: "Xiaomi MiMo V2 Flash",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "qianfan",
    name: "百度千帆",
    description: "百度智能云 千帆大模型平台",
    icon: "🔴",
    apiType: "openai-chat",
    baseUrl: "https://qianfan.baidubce.com/v2",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "deepseek-v3.2",
        name: "DeepSeek V3.2",
        inputTypes: ["text"],
        contextWindow: 98304,
        maxTokens: 32768,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "ernie-5.0-thinking-preview",
        name: "ERNIE 5.0 Thinking",
        inputTypes: ["text", "image"],
        contextWindow: 119000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "modelstudio",
    name: "ModelStudio (DashScope)",
    description: "Alibaba Cloud model service platform with Coding Plan support",
    icon: "🏗️",
    apiType: "openai-chat",
    baseUrl: "https://coding-intl.dashscope.aliyuncs.com/v1",
    apiKeyPlaceholder: "sk-...",
    requiresApiKey: true,
    models: [
      {
        id: "qwen3.7-plus",
        name: "Qwen 3.7 Plus",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "qwen3.6-plus",
        name: "Qwen 3.6 Plus",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "qwen3.5-plus",
        name: "Qwen 3.5 Plus",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 65536,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "qwen3-max-2026-01-23",
        name: "Qwen 3 Max",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 65536,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "qwen3-coder-plus",
        name: "Qwen 3 Coder Plus",
        inputTypes: ["text"],
        contextWindow: 1000000,
        maxTokens: 65536,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "qwen3-coder-next",
        name: "Qwen 3 Coder Next",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 65536,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "MiniMax-M2.5",
        name: "MiniMax M2.5",
        inputTypes: ["text"],
        contextWindow: 1000000,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "glm-5.1",
        name: "GLM-5.1",
        inputTypes: ["text"],
        contextWindow: 202800,
        maxTokens: 131100,
        reasoning: true,
        costInput: 1.2,
        costOutput: 4.0,
      },
      {
        id: "glm-5",
        name: "GLM-5",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "glm-4.7",
        name: "GLM 4.7",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "kimi-k2.6",
        name: "Kimi K2.6",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: false,
        costInput: 0.95,
        costOutput: 4.0,
      },
    ],
    thinkingStyle: "qwen",
  },
  {
    key: "tencent",
    name: "腾讯混元 (TokenHub)",
    description: "腾讯混元 Hy3 推理模型",
    icon: "🐧",
    apiType: "openai-chat",
    baseUrl: "https://tokenhub.tencentmaas.com/v1",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "hy3",
        name: "Hy3 (TokenHub)",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 0.176,
        costOutput: 0.587,
      },
      {
        id: "hy3-preview",
        name: "Hy3 Preview",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 0.176,
        costOutput: 0.587,
      },
    ],
  },
  {
    key: "stepfun",
    name: "阶跃星辰 (StepFun)",
    description: "Step 系列推理模型",
    icon: "🪜",
    apiType: "openai-chat",
    baseUrl: "https://api.stepfun.com/v1",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "step-3.7-flash",
        name: "Step 3.7 Flash",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: true,
        costInput: 0.2,
        costOutput: 1.15,
      },
      {
        id: "step-3.5-flash",
        name: "Step 3.5 Flash",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "step-3.5-flash-2603",
        name: "Step 3.5 Flash 2603",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
]
