import type { ProviderTemplate } from "../types"

export const infrastructureTemplates: ProviderTemplate[] = [
  // ── 基础设施 / 聚合 Provider ──
  {
    key: "openrouter",
    name: "OpenRouter",
    description: "多模型聚合网关，一个 Key 用数百个模型",
    icon: "🔀",
    apiType: "openai-chat",
    baseUrl: "https://openrouter.ai/api/v1",
    apiKeyPlaceholder: "sk-or-...",
    requiresApiKey: true,
    models: [
      {
        id: "auto",
        name: "OpenRouter Auto",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "anthropic/claude-opus-4-7",
        name: "Claude Opus 4.7",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 32000,
        reasoning: true,
        costInput: 15.0,
        costOutput: 75.0,
      },
      {
        id: "anthropic/claude-sonnet-4-6",
        name: "Claude Sonnet 4.6",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 3.0,
        costOutput: 15.0,
      },
      {
        id: "openai/gpt-5.5",
        name: "GPT-5.5",
        inputTypes: ["text", "image"],
        contextWindow: 272000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 5.0,
        costOutput: 30.0,
      },
      {
        id: "openai/gpt-4o",
        name: "GPT-4o",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 2.5,
        costOutput: 10.0,
      },
      {
        id: "google/gemini-2.5-pro-preview",
        name: "Gemini 2.5 Pro",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 65536,
        reasoning: true,
        costInput: 1.25,
        costOutput: 10.0,
      },
      {
        id: "deepseek/deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        inputTypes: ["text"],
        contextWindow: 1000000,
        maxTokens: 384000,
        reasoning: true,
        costInput: 1.74,
        costOutput: 3.48,
      },
      {
        id: "deepseek/deepseek-v4-flash",
        name: "DeepSeek V4 Flash",
        inputTypes: ["text"],
        contextWindow: 1000000,
        maxTokens: 384000,
        reasoning: true,
        costInput: 0.14,
        costOutput: 0.28,
      },
      {
        id: "deepseek/deepseek-r1",
        name: "DeepSeek R1",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0.55,
        costOutput: 2.19,
      },
      {
        id: "moonshotai/kimi-k2.6",
        name: "Kimi K2.6",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: false,
        costInput: 0.95,
        costOutput: 4.0,
      },
      {
        id: "openrouter/hunter-alpha",
        name: "Hunter Alpha",
        inputTypes: ["text"],
        contextWindow: 1048576,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "openrouter/healer-alpha",
        name: "Healer Alpha",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "groq",
    name: "Groq",
    description: "超高速 LPU 推理",
    icon: "🚀",
    apiType: "openai-chat",
    baseUrl: "https://api.groq.com/openai",
    apiKeyPlaceholder: "gsk_...",
    requiresApiKey: true,
    models: [
      {
        id: "llama-3.3-70b-versatile",
        name: "Llama 3.3 70B",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0.59,
        costOutput: 0.79,
      },
      {
        id: "mixtral-8x7b-32768",
        name: "Mixtral 8x7B",
        inputTypes: ["text"],
        contextWindow: 32768,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0.24,
        costOutput: 0.24,
      },
    ],
  },
  {
    key: "nvidia",
    name: "NVIDIA",
    description: "NVIDIA AI Endpoints",
    icon: "💚",
    apiType: "openai-chat",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    apiKeyPlaceholder: "nvapi-...",
    requiresApiKey: true,
    models: [
      {
        id: "nvidia/nemotron-3-super-120b-a12b",
        name: "Nemotron 3 Super 120B",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "moonshotai/kimi-k2.5",
        name: "Kimi K2.5",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "minimaxai/minimax-m2.5",
        name: "MiniMax M2.5",
        inputTypes: ["text"],
        contextWindow: 196608,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "z-ai/glm5",
        name: "GLM-5",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "together",
    name: "Together AI",
    description: "开源模型云推理平台",
    icon: "🤝",
    apiType: "openai-chat",
    baseUrl: "https://api.together.xyz/v1",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        name: "Llama 3.3 70B Turbo",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.88,
        costOutput: 0.88,
      },
      {
        id: "moonshotai/Kimi-K2.5",
        name: "Kimi K2.5",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 32768,
        reasoning: true,
        costInput: 0.5,
        costOutput: 2.8,
      },
      {
        id: "zai-org/GLM-4.7",
        name: "GLM 4.7 Fp8",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.45,
        costOutput: 2.0,
      },
      {
        id: "meta-llama/Llama-4-Scout-17B-16E-Instruct",
        name: "Llama 4 Scout 17B",
        inputTypes: ["text", "image"],
        contextWindow: 10000000,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0.18,
        costOutput: 0.59,
      },
      {
        id: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
        name: "Llama 4 Maverick 17B",
        inputTypes: ["text", "image"],
        contextWindow: 20000000,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0.27,
        costOutput: 0.85,
      },
      {
        id: "deepseek-ai/DeepSeek-V3.1",
        name: "DeepSeek V3.1",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.6,
        costOutput: 1.25,
      },
      {
        id: "deepseek-ai/DeepSeek-R1",
        name: "DeepSeek R1",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: true,
        costInput: 3.0,
        costOutput: 7.0,
      },
      {
        id: "moonshotai/Kimi-K2-Instruct-0905",
        name: "Kimi K2 Instruct",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 8192,
        reasoning: false,
        costInput: 1.0,
        costOutput: 3.0,
      },
    ],
  },
  {
    key: "huggingface",
    name: "Hugging Face",
    description: "HF Inference API 开源模型推理",
    icon: "🤗",
    apiType: "openai-chat",
    baseUrl: "https://router.huggingface.co/v1",
    apiKeyPlaceholder: "hf_...",
    requiresApiKey: true,
    models: [
      {
        id: "deepseek-ai/DeepSeek-V3.1",
        name: "DeepSeek V3.1",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.6,
        costOutput: 1.25,
      },
      {
        id: "deepseek-ai/DeepSeek-R1",
        name: "DeepSeek R1",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: true,
        costInput: 3.0,
        costOutput: 7.0,
      },
      {
        id: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        name: "Llama 3.3 70B Turbo",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.88,
        costOutput: 0.88,
      },
      {
        id: "openai/gpt-oss-120b",
        name: "GPT-OSS 120B",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "byteplus",
    name: "BytePlus (海外火山)",
    description: "BytePlus AI 国际版大模型平台",
    icon: "🔥",
    apiType: "openai-chat",
    baseUrl: "https://ark.ap-southeast.bytepluses.com/api/v3",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "seed-1-8-251228",
        name: "Seed 1.8",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "kimi-k2-5-260127",
        name: "Kimi K2.5",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 32768,
        reasoning: true,
        costInput: 0.6,
        costOutput: 2.5,
      },
      {
        id: "glm-4-7-251222",
        name: "GLM 4.7",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "chutes",
    name: "Chutes (TEE)",
    description: "TEE 可信执行环境 AI 推理",
    icon: "🔒",
    apiType: "openai-chat",
    baseUrl: "https://llm.chutes.ai/v1",
    apiKeyPlaceholder: "cpk_...",
    requiresApiKey: true,
    models: [
      {
        id: "zai-org/GLM-5-TEE",
        name: "GLM-5 TEE",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 65535,
        reasoning: true,
        costInput: 0.95,
        costOutput: 3.15,
      },
      {
        id: "zai-org/GLM-4.7-TEE",
        name: "GLM-4.7 TEE",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 65535,
        reasoning: true,
        costInput: 0.4,
        costOutput: 2.0,
      },
      {
        id: "zai-org/GLM-4.7-FP8",
        name: "GLM-4.7 FP8",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 65535,
        reasoning: true,
        costInput: 0.3,
        costOutput: 1.2,
      },
      {
        id: "zai-org/GLM-4.6-TEE",
        name: "GLM-4.6 TEE",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.4,
        costOutput: 1.7,
      },
      {
        id: "zai-org/GLM-4.6-FP8",
        name: "GLM-4.6 FP8",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 65535,
        reasoning: true,
        costInput: 0.3,
        costOutput: 1.2,
      },
      {
        id: "zai-org/GLM-4.6V",
        name: "GLM-4.6V",
        inputTypes: ["text", "image"],
        contextWindow: 131072,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.3,
        costOutput: 0.9,
      },
      {
        id: "moonshotai/Kimi-K2.5-TEE",
        name: "Kimi K2.5 TEE",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 65535,
        reasoning: true,
        costInput: 0.45,
        costOutput: 2.2,
      },
      {
        id: "deepseek-ai/DeepSeek-V3-0324-TEE",
        name: "DeepSeek V3 TEE",
        inputTypes: ["text"],
        contextWindow: 163840,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.25,
        costOutput: 1.0,
      },
      {
        id: "deepseek-ai/DeepSeek-V3.1-TEE",
        name: "DeepSeek V3.1 TEE",
        inputTypes: ["text"],
        contextWindow: 163840,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.2,
        costOutput: 0.8,
      },
      {
        id: "deepseek-ai/DeepSeek-V3.1-Terminus-TEE",
        name: "DeepSeek V3.1 Terminus TEE",
        inputTypes: ["text"],
        contextWindow: 163840,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.23,
        costOutput: 0.9,
      },
      {
        id: "deepseek-ai/DeepSeek-V3.2-TEE",
        name: "DeepSeek V3.2 TEE",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.28,
        costOutput: 0.42,
      },
      {
        id: "deepseek-ai/DeepSeek-R1-0528-TEE",
        name: "DeepSeek R1 0528 TEE",
        inputTypes: ["text"],
        contextWindow: 163840,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.45,
        costOutput: 2.15,
      },
      {
        id: "MiniMaxAI/MiniMax-M2.5-TEE",
        name: "MiniMax M2.5 TEE",
        inputTypes: ["text"],
        contextWindow: 196608,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.3,
        costOutput: 1.1,
      },
      {
        id: "XiaomiMiMo/MiMo-V2-Flash-TEE",
        name: "MiMo V2 Flash TEE",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.09,
        costOutput: 0.29,
      },
      {
        id: "openai/gpt-oss-120b-TEE",
        name: "GPT-OSS 120B TEE",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.05,
        costOutput: 0.45,
      },
      {
        id: "Qwen/Qwen3-235B-A22B-Instruct-2507-TEE",
        name: "Qwen 3 235B TEE",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.08,
        costOutput: 0.55,
      },
      {
        id: "Qwen/Qwen3-235B-A22B-Thinking-2507",
        name: "Qwen 3 235B Thinking",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: true,
        costInput: 0.11,
        costOutput: 0.6,
      },
      {
        id: "Qwen/Qwen3.5-397B-A17B-TEE",
        name: "Qwen 3.5 397B TEE",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.55,
        costOutput: 3.5,
      },
      {
        id: "Qwen/Qwen3-Coder-Next-TEE",
        name: "Qwen 3 Coder Next TEE",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.12,
        costOutput: 0.75,
      },
      {
        id: "Qwen/Qwen3-32B",
        name: "Qwen 3 32B",
        inputTypes: ["text"],
        contextWindow: 40960,
        maxTokens: 40960,
        reasoning: true,
        costInput: 0.08,
        costOutput: 0.24,
      },
    ],
  },
  {
    key: "fireworks",
    name: "Fireworks AI",
    description: "高性能模型推理平台",
    icon: "🎆",
    apiType: "openai-chat",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    apiKeyPlaceholder: "fw_...",
    requiresApiKey: true,
    models: [
      {
        id: "accounts/fireworks/models/kimi-k2p6",
        name: "Kimi K2.6",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: false,
        costInput: 0.95,
        costOutput: 4.0,
      },
      {
        id: "accounts/fireworks/routers/kimi-k2p5-turbo",
        name: "Kimi K2.5 Turbo (Fire Pass)",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 256000,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "arcee",
    name: "Arcee",
    description: "Arcee Trinity 系列模型",
    icon: "🏹",
    apiType: "openai-chat",
    baseUrl: "https://api.arcee.ai/api/v1",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "trinity-large-thinking",
        name: "Trinity Large Thinking",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 80000,
        reasoning: true,
        costInput: 0.25,
        costOutput: 0.9,
      },
      {
        id: "trinity-large-preview",
        name: "Trinity Large Preview",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0.25,
        costOutput: 1.0,
      },
      {
        id: "trinity-mini",
        name: "Trinity Mini 26B",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 80000,
        reasoning: false,
        costInput: 0.045,
        costOutput: 0.15,
      },
    ],
  },
  {
    key: "venice",
    name: "Venice",
    description: "隐私优先 AI 推理平台",
    icon: "🎭",
    apiType: "openai-chat",
    baseUrl: "https://api.venice.ai/api/v1",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "kimi-k2-5",
        name: "Kimi K2.5",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "deepseek-v3.2",
        name: "DeepSeek V3.2",
        inputTypes: ["text"],
        contextWindow: 160000,
        maxTokens: 32768,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "qwen3-coder-480b-a35b-instruct",
        name: "Qwen 3 Coder 480B",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 65536,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "qwen3-5-35b-a3b",
        name: "Qwen 3.5 35B",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "zai-org-glm-5",
        name: "GLM-5",
        inputTypes: ["text"],
        contextWindow: 198000,
        maxTokens: 32000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "minimax-m25",
        name: "MiniMax M2.5",
        inputTypes: ["text"],
        contextWindow: 198000,
        maxTokens: 32768,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "llama-3.3-70b",
        name: "Llama 3.3 70B",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "openai-gpt-oss-120b",
        name: "GPT-OSS 120B",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "synthetic",
    name: "Synthetic",
    description: "开源模型推理 (Anthropic 兼容)",
    icon: "🧬",
    apiType: "anthropic",
    baseUrl: "https://api.synthetic.new/anthropic",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "hf:MiniMaxAI/MiniMax-M2.5",
        name: "MiniMax M2.5",
        inputTypes: ["text"],
        contextWindow: 192000,
        maxTokens: 65536,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "hf:moonshotai/Kimi-K2.5",
        name: "Kimi K2.5",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "hf:moonshotai/Kimi-K2-Thinking",
        name: "Kimi K2 Thinking",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "hf:Qwen/Qwen3-235B-A22B-Thinking-2507",
        name: "Qwen 3 235B Thinking",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "hf:Qwen/Qwen3-VL-235B-A22B-Instruct",
        name: "Qwen 3 VL 235B",
        inputTypes: ["text", "image"],
        contextWindow: 250000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "hf:zai-org/GLM-5",
        name: "GLM-5",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "hf:zai-org/GLM-4.7",
        name: "GLM-4.7",
        inputTypes: ["text"],
        contextWindow: 198000,
        maxTokens: 128000,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "hf:deepseek-ai/DeepSeek-V3.2",
        name: "DeepSeek V3.2",
        inputTypes: ["text"],
        contextWindow: 159000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "hf:deepseek-ai/DeepSeek-R1-0528",
        name: "DeepSeek R1 0528",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "hf:Qwen/Qwen3-Coder-480B-A35B-Instruct",
        name: "Qwen 3 Coder 480B",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "hf:openai/gpt-oss-120b",
        name: "GPT-OSS 120B",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
    thinkingStyle: "anthropic",
  },
  {
    key: "vercel-ai-gateway",
    name: "Vercel AI Gateway",
    description: "Vercel AI 网关代理",
    icon: "▲",
    apiType: "openai-chat",
    baseUrl: "https://ai-gateway.vercel.sh",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "anthropic/claude-opus-4.7",
        name: "Claude Opus 4.7",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 5.0,
        costOutput: 25.0,
      },
      {
        id: "anthropic/claude-opus-4.6",
        name: "Claude Opus 4.6",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 5.0,
        costOutput: 25.0,
      },
      {
        id: "openai/gpt-5.5",
        name: "GPT-5.5",
        inputTypes: ["text", "image"],
        contextWindow: 272000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 5.0,
        costOutput: 30.0,
      },
      {
        id: "openai/gpt-5.4",
        name: "GPT-5.4",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 2.5,
        costOutput: 15.0,
      },
      {
        id: "openai/gpt-5.4-pro",
        name: "GPT-5.4 Pro",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 30.0,
        costOutput: 180.0,
      },
      {
        id: "moonshotai/kimi-k2.6",
        name: "Kimi K2.6",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: true,
        costInput: 0.95,
        costOutput: 4.0,
      },
    ],
  },
  {
    key: "cloudflare-ai",
    name: "Cloudflare AI Gateway",
    description: "Cloudflare AI 网关代理",
    icon: "☁️",
    apiType: "openai-chat",
    baseUrl: "https://gateway.ai.cloudflare.com/v1/{accountId}/{gatewayId}",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "claude-sonnet-4-6",
        name: "Claude Sonnet 4.6",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 3.0,
        costOutput: 15.0,
      },
    ],
  },
  {
    key: "cerebras",
    name: "Cerebras",
    description: "Cerebras 超快推理 (Wafer Scale)",
    icon: "🟧",
    apiType: "openai-chat",
    baseUrl: "https://api.cerebras.ai/v1",
    apiKeyPlaceholder: "csk-...",
    requiresApiKey: true,
    models: [
      {
        id: "zai-glm-4.7",
        name: "Z.ai GLM 4.7",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 2.25,
        costOutput: 2.75,
      },
      {
        id: "gpt-oss-120b",
        name: "GPT OSS 120B",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0.35,
        costOutput: 0.75,
      },
      {
        id: "qwen-3-235b-a22b-instruct-2507",
        name: "Qwen 3 235B Instruct",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.6,
        costOutput: 1.2,
      },
      {
        id: "llama3.1-8b",
        name: "Llama 3.1 8B",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.1,
        costOutput: 0.1,
      },
    ],
  },
  {
    key: "deepinfra",
    name: "DeepInfra",
    description: "性价比开源模型推理平台",
    icon: "♾️",
    apiType: "openai-chat",
    baseUrl: "https://api.deepinfra.com/v1/openai",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "deepseek-ai/DeepSeek-V3.2",
        name: "DeepSeek V3.2",
        inputTypes: ["text"],
        contextWindow: 163840,
        maxTokens: 163840,
        reasoning: false,
        costInput: 0.26,
        costOutput: 0.38,
      },
      {
        id: "zai-org/GLM-5.1",
        name: "GLM-5.1",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 202752,
        reasoning: true,
        costInput: 1.05,
        costOutput: 3.5,
      },
      {
        id: "MiniMaxAI/MiniMax-M2.5",
        name: "MiniMax M2.5",
        inputTypes: ["text"],
        contextWindow: 196608,
        maxTokens: 196608,
        reasoning: true,
        costInput: 0.15,
        costOutput: 1.15,
      },
      {
        id: "moonshotai/Kimi-K2.5",
        name: "Kimi K2.5",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: true,
        costInput: 0.45,
        costOutput: 2.25,
      },
      {
        id: "stepfun-ai/Step-3.5-Flash",
        name: "Step 3.5 Flash",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: false,
        costInput: 0.1,
        costOutput: 0.3,
      },
      {
        id: "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B",
        name: "NVIDIA Nemotron 3 Super 120B",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: true,
        costInput: 0.1,
        costOutput: 0.5,
      },
      {
        id: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        name: "Llama 3.3 70B Turbo",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 131072,
        reasoning: false,
        costInput: 0.1,
        costOutput: 0.32,
      },
    ],
  },
]
