import type { ProviderTemplate } from "../types"

export const infrastructureTemplates: ProviderTemplate[] = [
  // ── 基础设施 / 聚合 Provider ──
  {
    key: "openrouter",
    name: "OpenRouter",
    description: "多模型聚合网关，一个 Key 用数百个模型",
    icon: "🔀",
    apiType: "openai-chat",
    baseUrl: "https://openrouter.ai/api/v1",
    apiKeyPlaceholder: "sk-or-...",
    requiresApiKey: true,
    models: [
      {
        id: "auto",
        name: "OpenRouter Auto",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "anthropic/claude-opus-4-8",
        name: "Claude Opus 4.8",
        inputTypes: ["text", "image"],
        contextWindow: 1048576,
        maxTokens: 128000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "anthropic/claude-sonnet-4-6",
        name: "Claude Sonnet 4.6",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 3.0,
        costOutput: 15.0,
      },
      {
        id: "openai/gpt-5.5",
        name: "GPT-5.5",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 5.0,
        costOutput: 30.0,
      },
      {
        id: "openai/gpt-5.4",
        name: "GPT-5.4",
        inputTypes: ["text", "image"],
        contextWindow: 272000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 2.5,
        costOutput: 15.0,
      },
      {
        id: "openai/gpt-4o",
        name: "GPT-4o",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 2.5,
        costOutput: 10.0,
      },
      {
        id: "google/gemini-3.1-pro-preview",
        name: "Gemini 3.1 Pro Preview",
        inputTypes: ["text", "image"],
        contextWindow: 1048576,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "deepseek/deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        inputTypes: ["text"],
        contextWindow: 1000000,
        maxTokens: 384000,
        reasoning: true,
        costInput: 1.74,
        costOutput: 3.48,
      },
      {
        id: "deepseek/deepseek-v4-flash",
        name: "DeepSeek V4 Flash",
        inputTypes: ["text"],
        contextWindow: 1000000,
        maxTokens: 384000,
        reasoning: true,
        costInput: 0.14,
        costOutput: 0.28,
      },
      {
        id: "deepseek/deepseek-r1",
        name: "DeepSeek R1",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0.55,
        costOutput: 2.19,
      },
      {
        id: "moonshotai/kimi-k2.6",
        name: "Kimi K2.6",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: false,
        costInput: 0.8,
        costOutput: 3.5,
      },
      {
        id: "z-ai/glm-5.1",
        name: "GLM-5.1",
        inputTypes: ["text"],
        contextWindow: 202800,
        maxTokens: 131100,
        reasoning: true,
        costInput: 1.2,
        costOutput: 4.0,
      },
      {
        id: "openrouter/hunter-alpha",
        name: "Hunter Alpha",
        inputTypes: ["text"],
        contextWindow: 1048576,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "openrouter/healer-alpha",
        name: "Healer Alpha",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "groq",
    name: "Groq",
    description: "超高速 LPU 推理",
    icon: "🚀",
    apiType: "openai-chat",
    baseUrl: "https://api.groq.com/openai",
    apiKeyPlaceholder: "gsk_...",
    requiresApiKey: true,
    models: [
      {
        id: "groq/compound",
        name: "Compound",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "groq/compound-mini",
        name: "Compound Mini",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "meta-llama/llama-4-scout-17b-16e-instruct",
        name: "Llama 4 Scout 17B",
        inputTypes: ["text", "image"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.11,
        costOutput: 0.34,
      },
      {
        id: "openai/gpt-oss-120b",
        name: "GPT OSS 120B",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.15,
        costOutput: 0.6,
      },
      {
        id: "openai/gpt-oss-20b",
        name: "GPT OSS 20B",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.075,
        costOutput: 0.3,
      },
      {
        id: "openai/gpt-oss-safeguard-20b",
        name: "Safety GPT OSS 20B",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.075,
        costOutput: 0.3,
      },
      {
        id: "qwen/qwen3-32b",
        name: "Qwen3 32B",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 40960,
        reasoning: true,
        costInput: 0.29,
        costOutput: 0.59,
      },
      {
        id: "llama-3.3-70b-versatile",
        name: "Llama 3.3 70B Versatile",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0.59,
        costOutput: 0.79,
      },
      {
        id: "llama-3.1-8b-instant",
        name: "Llama 3.1 8B Instant",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 131072,
        reasoning: false,
        costInput: 0.05,
        costOutput: 0.08,
      },
      {
        id: "mixtral-8x7b-32768",
        name: "Mixtral 8x7B",
        inputTypes: ["text"],
        contextWindow: 32768,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0.24,
        costOutput: 0.24,
      },
    ],
  },
  {
    key: "nvidia",
    name: "NVIDIA",
    description: "NVIDIA AI Endpoints",
    icon: "💚",
    apiType: "openai-chat",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    apiKeyPlaceholder: "nvapi-...",
    requiresApiKey: true,
    models: [
      {
        id: "nvidia/nemotron-3-ultra-550b-a55b",
        name: "NVIDIA Nemotron 3 Ultra 550B",
        inputTypes: ["text"],
        contextWindow: 1048576,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "nvidia/nemotron-3-super-120b-a12b",
        name: "NVIDIA Nemotron 3 Super 120B",
        inputTypes: ["text"],
        contextWindow: 1000000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "z-ai/glm-5.2",
        name: "GLM 5.2",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "deepseek-ai/deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "qwen/qwen3.5-397b-a17b",
        name: "Qwen3.5 397B A17B",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "minimaxai/minimax-m3",
        name: "Minimax M3",
        inputTypes: ["text"],
        contextWindow: 196608,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "moonshotai/kimi-k2.6",
        name: "Kimi K2.6",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "moonshotai/kimi-k2.5",
        name: "Kimi K2.5",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "minimaxai/minimax-m2.7",
        name: "Minimax M2.7",
        inputTypes: ["text"],
        contextWindow: 196608,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "z-ai/glm-5.1",
        name: "GLM 5.1",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "minimaxai/minimax-m2.5",
        name: "MiniMax M2.5",
        inputTypes: ["text"],
        contextWindow: 196608,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "z-ai/glm5",
        name: "GLM-5",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "together",
    name: "Together AI",
    description: "开源模型云推理平台",
    icon: "🤝",
    apiType: "openai-chat",
    baseUrl: "https://api.together.xyz/v1",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "moonshotai/Kimi-K2.6",
        name: "Kimi K2.6 FP4",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 32768,
        reasoning: true,
        costInput: 1.2,
        costOutput: 4.5,
      },
      {
        id: "deepseek-ai/DeepSeek-V4-Pro",
        name: "DeepSeek V4 Pro",
        inputTypes: ["text"],
        contextWindow: 512000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 2.1,
        costOutput: 4.4,
      },
      {
        id: "zai-org/GLM-5.1",
        name: "GLM 5.1 FP4",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 8192,
        reasoning: true,
        costInput: 1.4,
        costOutput: 4.4,
      },
      {
        id: "zai-org/GLM-4.7",
        name: "GLM 4.7 Fp8",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.45,
        costOutput: 2.0,
      },
      {
        id: "meta-llama/Llama-4-Scout-17B-16E-Instruct",
        name: "Llama 4 Scout 17B",
        inputTypes: ["text", "image"],
        contextWindow: 10000000,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0.18,
        costOutput: 0.59,
      },
      {
        id: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
        name: "Llama 4 Maverick 17B",
        inputTypes: ["text", "image"],
        contextWindow: 20000000,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0.27,
        costOutput: 0.85,
      },
      {
        id: "moonshotai/Kimi-K2-Instruct-0905",
        name: "Kimi K2 Instruct",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 8192,
        reasoning: false,
        costInput: 1.0,
        costOutput: 3.0,
      },
      {
        id: "deepseek-ai/DeepSeek-V3.1",
        name: "DeepSeek V3.1",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.6,
        costOutput: 1.25,
      },
      {
        id: "deepseek-ai/DeepSeek-R1",
        name: "DeepSeek R1",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: true,
        costInput: 3.0,
        costOutput: 7.0,
      },
      {
        id: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        name: "Llama 3.3 70B Instruct Turbo",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.88,
        costOutput: 0.88,
      },
      {
        id: "Qwen/Qwen2.5-7B-Instruct-Turbo",
        name: "Qwen2.5 7B Instruct Turbo",
        inputTypes: ["text"],
        contextWindow: 32768,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.3,
        costOutput: 0.3,
      },
    ],
  },
  {
    key: "huggingface",
    name: "Hugging Face",
    description: "HF Inference API 开源模型推理",
    icon: "🤗",
    apiType: "openai-chat",
    baseUrl: "https://router.huggingface.co/v1",
    apiKeyPlaceholder: "hf_...",
    requiresApiKey: true,
    models: [
      {
        id: "deepseek-ai/DeepSeek-V3.1",
        name: "DeepSeek V3.1",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.6,
        costOutput: 1.25,
      },
      {
        id: "deepseek-ai/DeepSeek-R1",
        name: "DeepSeek R1",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: true,
        costInput: 3.0,
        costOutput: 7.0,
      },
      {
        id: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        name: "Llama 3.3 70B Turbo",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.88,
        costOutput: 0.88,
      },
      {
        id: "openai/gpt-oss-120b",
        name: "GPT-OSS 120B",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "byteplus",
    name: "BytePlus (海外火山)",
    description: "BytePlus AI 国际版大模型平台",
    icon: "🔥",
    apiType: "openai-chat",
    baseUrl: "https://ark.ap-southeast.bytepluses.com/api/v3",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "seed-1-8-251228",
        name: "Seed 1.8",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0.0001,
        costOutput: 0.0002,
      },
      {
        id: "kimi-k2-5-260127",
        name: "Kimi K2.5",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 32768,
        reasoning: true,
        costInput: 0.6,
        costOutput: 2.5,
      },
      {
        id: "glm-4-7-251222",
        name: "GLM 4.7",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0.0001,
        costOutput: 0.0002,
      },
    ],
  },
  {
    key: "chutes",
    name: "Chutes (TEE)",
    description: "TEE 可信执行环境 AI 推理",
    icon: "🔒",
    apiType: "openai-chat",
    baseUrl: "https://llm.chutes.ai/v1",
    apiKeyPlaceholder: "cpk_...",
    requiresApiKey: true,
    models: [
      {
        id: "zai-org/GLM-5-TEE",
        name: "GLM-5 TEE",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 65535,
        reasoning: true,
        costInput: 0.95,
        costOutput: 3.15,
      },
      {
        id: "zai-org/GLM-4.7-TEE",
        name: "GLM-4.7 TEE",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 65535,
        reasoning: true,
        costInput: 0.4,
        costOutput: 2.0,
      },
      {
        id: "zai-org/GLM-4.7-FP8",
        name: "GLM-4.7 FP8",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 65535,
        reasoning: true,
        costInput: 0.3,
        costOutput: 1.2,
      },
      {
        id: "zai-org/GLM-4.6-TEE",
        name: "GLM-4.6 TEE",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.4,
        costOutput: 1.7,
      },
      {
        id: "zai-org/GLM-4.6-FP8",
        name: "GLM-4.6 FP8",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 65535,
        reasoning: true,
        costInput: 0.3,
        costOutput: 1.2,
      },
      {
        id: "zai-org/GLM-4.6V",
        name: "GLM-4.6V",
        inputTypes: ["text", "image"],
        contextWindow: 131072,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.3,
        costOutput: 0.9,
      },
      {
        id: "moonshotai/Kimi-K2.5-TEE",
        name: "Kimi K2.5 TEE",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 65535,
        reasoning: true,
        costInput: 0.45,
        costOutput: 2.2,
      },
      {
        id: "deepseek-ai/DeepSeek-V3.2-TEE",
        name: "DeepSeek V3.2 TEE",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.28,
        costOutput: 0.42,
      },
      {
        id: "deepseek-ai/DeepSeek-V3.1-Terminus-TEE",
        name: "DeepSeek V3.1 Terminus TEE",
        inputTypes: ["text"],
        contextWindow: 163840,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.23,
        costOutput: 0.9,
      },
      {
        id: "deepseek-ai/DeepSeek-V3.1-TEE",
        name: "DeepSeek V3.1 TEE",
        inputTypes: ["text"],
        contextWindow: 163840,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.2,
        costOutput: 0.8,
      },
      {
        id: "deepseek-ai/DeepSeek-V3-0324-TEE",
        name: "DeepSeek V3 TEE",
        inputTypes: ["text"],
        contextWindow: 163840,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.25,
        costOutput: 1.0,
      },
      {
        id: "deepseek-ai/DeepSeek-R1-0528-TEE",
        name: "DeepSeek R1 0528 TEE",
        inputTypes: ["text"],
        contextWindow: 163840,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.45,
        costOutput: 2.15,
      },
      {
        id: "MiniMaxAI/MiniMax-M2.5-TEE",
        name: "MiniMax M2.5 TEE",
        inputTypes: ["text"],
        contextWindow: 196608,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.3,
        costOutput: 1.1,
      },
      {
        id: "XiaomiMiMo/MiMo-V2-Flash-TEE",
        name: "MiMo V2 Flash TEE",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.09,
        costOutput: 0.29,
      },
      {
        id: "openai/gpt-oss-120b-TEE",
        name: "GPT-OSS 120B TEE",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.05,
        costOutput: 0.45,
      },
      {
        id: "NousResearch/Hermes-4-405B-FP8-TEE",
        name: "Hermes 4 405B FP8 TEE",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.3,
        costOutput: 1.2,
      },
      {
        id: "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16-TEE",
        name: "NVIDIA Nemotron 3 Nano 30B TEE",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 4096,
        reasoning: true,
        costInput: 0.3,
        costOutput: 1.2,
      },
      {
        id: "Qwen/Qwen3.5-397B-A17B-TEE",
        name: "Qwen 3.5 397B TEE",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.55,
        costOutput: 3.5,
      },
      {
        id: "Qwen/Qwen3-235B-A22B-Instruct-2507-TEE",
        name: "Qwen 3 235B TEE",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.08,
        costOutput: 0.55,
      },
      {
        id: "Qwen/Qwen3-Coder-Next-TEE",
        name: "Qwen 3 Coder Next TEE",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.12,
        costOutput: 0.75,
      },
      {
        id: "Qwen/Qwen3-235B-A22B-Thinking-2507",
        name: "Qwen 3 235B Thinking",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: true,
        costInput: 0.11,
        costOutput: 0.6,
      },
      {
        id: "Qwen/Qwen3-VL-235B-A22B-Instruct",
        name: "Qwen3-VL 235B Instruct",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: false,
        costInput: 0.3,
        costOutput: 1.2,
      },
      {
        id: "Qwen/Qwen3-Next-80B-A3B-Instruct",
        name: "Qwen3-Next 80B Instruct",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: false,
        costInput: 0.1,
        costOutput: 0.8,
      },
      {
        id: "Qwen/Qwen3-32B",
        name: "Qwen 3 32B",
        inputTypes: ["text"],
        contextWindow: 40960,
        maxTokens: 40960,
        reasoning: true,
        costInput: 0.08,
        costOutput: 0.24,
      },
      {
        id: "Qwen/Qwen3-30B-A3B",
        name: "Qwen3 30B A3B",
        inputTypes: ["text"],
        contextWindow: 40960,
        maxTokens: 40960,
        reasoning: true,
        costInput: 0.06,
        costOutput: 0.22,
      },
      {
        id: "Qwen/Qwen3-14B",
        name: "Qwen3 14B",
        inputTypes: ["text"],
        contextWindow: 40960,
        maxTokens: 40960,
        reasoning: true,
        costInput: 0.05,
        costOutput: 0.22,
      },
      {
        id: "tngtech/DeepSeek-TNG-R1T2-Chimera",
        name: "DeepSeek TNG R1T2 Chimera",
        inputTypes: ["text"],
        contextWindow: 163840,
        maxTokens: 163840,
        reasoning: true,
        costInput: 0.25,
        costOutput: 0.85,
      },
      {
        id: "tngtech/R1T2-Chimera-Speed",
        name: "R1T2 Chimera Speed",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.22,
        costOutput: 0.6,
      },
      {
        id: "deepseek-ai/DeepSeek-V3",
        name: "DeepSeek V3",
        inputTypes: ["text"],
        contextWindow: 163840,
        maxTokens: 163840,
        reasoning: false,
        costInput: 0.3,
        costOutput: 1.2,
      },
      {
        id: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
        name: "DeepSeek R1 Distill Llama 70B",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 131072,
        reasoning: true,
        costInput: 0.03,
        costOutput: 0.11,
      },
      {
        id: "openai/gpt-oss-20b",
        name: "GPT-OSS 20B",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 131072,
        reasoning: true,
        costInput: 0.04,
        costOutput: 0.15,
      },
      {
        id: "NousResearch/Hermes-4-14B",
        name: "Hermes 4 14B",
        inputTypes: ["text"],
        contextWindow: 40960,
        maxTokens: 40960,
        reasoning: true,
        costInput: 0.01,
        costOutput: 0.05,
      },
      {
        id: "NousResearch/DeepHermes-3-Mistral-24B-Preview",
        name: "DeepHermes 3 Mistral 24B",
        inputTypes: ["text"],
        contextWindow: 32768,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0.02,
        costOutput: 0.1,
      },
      {
        id: "chutesai/Mistral-Small-3.2-24B-Instruct-2506",
        name: "Mistral Small 3.2 24B Instruct",
        inputTypes: ["text", "image"],
        contextWindow: 131072,
        maxTokens: 131072,
        reasoning: false,
        costInput: 0.06,
        costOutput: 0.18,
      },
      {
        id: "chutesai/Mistral-Small-3.1-24B-Instruct-2503",
        name: "Mistral Small 3.1 24B Instruct",
        inputTypes: ["text", "image"],
        contextWindow: 131072,
        maxTokens: 131072,
        reasoning: false,
        costInput: 0.03,
        costOutput: 0.11,
      },
      {
        id: "unsloth/Mistral-Small-24B-Instruct-2501",
        name: "Mistral Small 24B Instruct 2501",
        inputTypes: ["text", "image"],
        contextWindow: 32768,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0.07,
        costOutput: 0.3,
      },
      {
        id: "unsloth/Mistral-Nemo-Instruct-2407",
        name: "Mistral Nemo Instruct 2407",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 131072,
        reasoning: false,
        costInput: 0.02,
        costOutput: 0.04,
      },
      {
        id: "Qwen/Qwen2.5-72B-Instruct",
        name: "Qwen2.5 72B Instruct",
        inputTypes: ["text"],
        contextWindow: 32768,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0.3,
        costOutput: 1.2,
      },
      {
        id: "Qwen/Qwen2.5-Coder-32B-Instruct",
        name: "Qwen2.5 Coder 32B Instruct",
        inputTypes: ["text"],
        contextWindow: 32768,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0.03,
        costOutput: 0.11,
      },
      {
        id: "Qwen/Qwen2.5-VL-32B-Instruct",
        name: "Qwen2.5-VL 32B Instruct",
        inputTypes: ["text", "image"],
        contextWindow: 16384,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0.05,
        costOutput: 0.22,
      },
      {
        id: "unsloth/gemma-3-27b-it",
        name: "Gemma 3 27B",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 65536,
        reasoning: false,
        costInput: 0.04,
        costOutput: 0.15,
      },
      {
        id: "unsloth/gemma-3-12b-it",
        name: "Gemma 3 12B",
        inputTypes: ["text", "image"],
        contextWindow: 131072,
        maxTokens: 131072,
        reasoning: false,
        costInput: 0.03,
        costOutput: 0.1,
      },
      {
        id: "unsloth/gemma-3-4b-it",
        name: "Gemma 3 4B",
        inputTypes: ["text", "image"],
        contextWindow: 96000,
        maxTokens: 96000,
        reasoning: false,
        costInput: 0.01,
        costOutput: 0.03,
      },
      {
        id: "unsloth/Llama-3.2-3B-Instruct",
        name: "Llama 3.2 3B Instruct",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0.01,
        costOutput: 0.01,
      },
      {
        id: "unsloth/Llama-3.2-1B-Instruct",
        name: "Llama 3.2 1B Instruct",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0.01,
        costOutput: 0.01,
      },
      {
        id: "Qwen/Qwen3Guard-Gen-0.6B",
        name: "Qwen3Guard Gen 0.6B",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0.01,
        costOutput: 0.01,
      },
      {
        id: "rednote-hilab/dots.ocr",
        name: "dots.ocr",
        inputTypes: ["text", "image"],
        contextWindow: 131072,
        maxTokens: 131072,
        reasoning: false,
        costInput: 0.01,
        costOutput: 0.01,
      },
    ],
  },
  {
    key: "fireworks",
    name: "Fireworks AI",
    description: "高性能模型推理平台",
    icon: "🎆",
    apiType: "openai-chat",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    apiKeyPlaceholder: "fw_...",
    requiresApiKey: true,
    models: [
      {
        id: "accounts/fireworks/models/kimi-k2p6",
        name: "Kimi K2.6",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: false,
        costInput: 0.95,
        costOutput: 4.0,
      },
      {
        id: "accounts/fireworks/routers/kimi-k2p5-turbo",
        name: "Kimi K2.5 Turbo (Fire Pass)",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 256000,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "arcee",
    name: "Arcee",
    description: "Arcee Trinity 系列模型",
    icon: "🏹",
    apiType: "openai-chat",
    baseUrl: "https://api.arcee.ai/api/v1",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "trinity-large-thinking",
        name: "Trinity Large Thinking",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 80000,
        reasoning: true,
        costInput: 0.25,
        costOutput: 0.9,
      },
      {
        id: "trinity-large-preview",
        name: "Trinity Large Preview",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0.25,
        costOutput: 1.0,
      },
      {
        id: "trinity-mini",
        name: "Trinity Mini 26B",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 80000,
        reasoning: false,
        costInput: 0.045,
        costOutput: 0.15,
      },
    ],
  },
  {
    key: "venice",
    name: "Venice",
    description: "隐私优先 AI 推理平台",
    icon: "🎭",
    apiType: "openai-chat",
    baseUrl: "https://api.venice.ai/api/v1",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "claude-opus-4-6",
        name: "Claude Opus 4.6 (via Venice)",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "claude-sonnet-4-6",
        name: "Claude Sonnet 4.6 (via Venice)",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "openai-gpt-54",
        name: "GPT-5.4 (via Venice)",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 131072,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "openai-gpt-53-codex",
        name: "GPT-5.3 Codex (via Venice)",
        inputTypes: ["text", "image"],
        contextWindow: 400000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "openai-gpt-52",
        name: "GPT-5.2 (via Venice)",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "openai-gpt-52-codex",
        name: "GPT-5.2 Codex (via Venice)",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "gemini-3-1-pro-preview",
        name: "Gemini 3.1 Pro (via Venice)",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 32768,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "gemini-3-pro-preview",
        name: "Gemini 3 Pro (via Venice)",
        inputTypes: ["text", "image"],
        contextWindow: 198000,
        maxTokens: 32768,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "gemini-3-flash-preview",
        name: "Gemini 3 Flash (via Venice)",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "grok-41-fast",
        name: "Grok 4.1 Fast (via Venice)",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 30000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "zai-org-glm-5",
        name: "GLM 5",
        inputTypes: ["text"],
        contextWindow: 198000,
        maxTokens: 32000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "zai-org-glm-4.7",
        name: "GLM 4.7",
        inputTypes: ["text"],
        contextWindow: 198000,
        maxTokens: 16384,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "zai-org-glm-4.7-flash",
        name: "GLM 4.7 Flash",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "olafangensan-glm-4.7-flash-heretic",
        name: "GLM 4.7 Flash Heretic",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 24000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "zai-org-glm-4.6",
        name: "GLM 4.6",
        inputTypes: ["text"],
        contextWindow: 198000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "kimi-k2-5",
        name: "Kimi K2.5",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "kimi-k2-thinking",
        name: "Kimi K2 Thinking",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "minimax-m25",
        name: "MiniMax M2.5",
        inputTypes: ["text"],
        contextWindow: 198000,
        maxTokens: 32768,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "minimax-m21",
        name: "MiniMax M2.1",
        inputTypes: ["text"],
        contextWindow: 198000,
        maxTokens: 32768,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "qwen3-5-35b-a3b",
        name: "Qwen3.5 35B A3B",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "qwen3-235b-a22b-thinking-2507",
        name: "Qwen3 235B Thinking",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "qwen3-235b-a22b-instruct-2507",
        name: "Qwen3 235B Instruct",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "qwen3-coder-480b-a35b-instruct",
        name: "Qwen3 Coder 480B",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 65536,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "qwen3-coder-480b-a35b-instruct-turbo",
        name: "Qwen3 Coder 480B Turbo",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 65536,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "qwen3-next-80b",
        name: "Qwen3 Next 80B",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "qwen3-vl-235b-a22b",
        name: "Qwen3 VL 235B (Vision)",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "qwen3-4b",
        name: "Venice Small (Qwen3 4B)",
        inputTypes: ["text"],
        contextWindow: 32000,
        maxTokens: 4096,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "deepseek-v3.2",
        name: "DeepSeek V3.2",
        inputTypes: ["text"],
        contextWindow: 160000,
        maxTokens: 32768,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "openai-gpt-oss-120b",
        name: "OpenAI GPT OSS 120B",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "nvidia-nemotron-3-nano-30b-a3b",
        name: "NVIDIA Nemotron 3 Nano 30B",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "mistral-31-24b",
        name: "Venice Medium (Mistral)",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "venice-uncensored",
        name: "Venice Uncensored (Dolphin-Mistral)",
        inputTypes: ["text"],
        contextWindow: 32000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "google-gemma-3-27b-it",
        name: "Google Gemma 3 27B Instruct",
        inputTypes: ["text", "image"],
        contextWindow: 198000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "openai-gpt-4o-2024-11-20",
        name: "GPT-4o (via Venice)",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "openai-gpt-4o-mini-2024-07-18",
        name: "GPT-4o Mini (via Venice)",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "hermes-3-llama-3.1-405b",
        name: "Hermes 3 Llama 3.1 405B",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "llama-3.3-70b",
        name: "Llama 3.3 70B",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "llama-3.2-3b",
        name: "Llama 3.2 3B",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "synthetic",
    name: "Synthetic",
    description: "开源模型推理 (Anthropic 兼容)",
    icon: "🧬",
    apiType: "anthropic",
    baseUrl: "https://api.synthetic.new/anthropic",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "hf:MiniMaxAI/MiniMax-M2.5",
        name: "MiniMax M2.5",
        inputTypes: ["text"],
        contextWindow: 192000,
        maxTokens: 65536,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "hf:moonshotai/Kimi-K2.5",
        name: "Kimi K2.5",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "hf:moonshotai/Kimi-K2-Thinking",
        name: "Kimi K2 Thinking",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "hf:Qwen/Qwen3-235B-A22B-Thinking-2507",
        name: "Qwen 3 235B Thinking",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "hf:Qwen/Qwen3-VL-235B-A22B-Instruct",
        name: "Qwen 3 VL 235B",
        inputTypes: ["text", "image"],
        contextWindow: 250000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "hf:zai-org/GLM-5",
        name: "GLM-5",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "hf:zai-org/GLM-4.7",
        name: "GLM-4.7",
        inputTypes: ["text"],
        contextWindow: 198000,
        maxTokens: 128000,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "hf:deepseek-ai/DeepSeek-V3.2",
        name: "DeepSeek V3.2",
        inputTypes: ["text"],
        contextWindow: 159000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "hf:deepseek-ai/DeepSeek-R1-0528",
        name: "DeepSeek R1 0528",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "hf:Qwen/Qwen3-Coder-480B-A35B-Instruct",
        name: "Qwen 3 Coder 480B",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "hf:openai/gpt-oss-120b",
        name: "GPT-OSS 120B",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
    thinkingStyle: "anthropic",
  },
  {
    key: "vercel-ai-gateway",
    name: "Vercel AI Gateway",
    description: "Vercel AI 网关代理",
    icon: "▲",
    apiType: "openai-chat",
    baseUrl: "https://ai-gateway.vercel.sh",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "anthropic/claude-opus-4.8",
        name: "Claude Opus 4.8",
        inputTypes: ["text", "image"],
        contextWindow: 1048576,
        maxTokens: 128000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "anthropic/claude-opus-4.6",
        name: "Claude Opus 4.6",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 5.0,
        costOutput: 25.0,
      },
      {
        id: "anthropic/claude-sonnet-4.6",
        name: "Claude Sonnet 4.6",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "openai/gpt-5.5",
        name: "GPT-5.5",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 5.0,
        costOutput: 30.0,
      },
      {
        id: "openai/gpt-5.4-pro",
        name: "GPT-5.4 Pro",
        inputTypes: ["text", "image"],
        contextWindow: 1050000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 30.0,
        costOutput: 180.0,
      },
      {
        id: "openai/gpt-5.4",
        name: "GPT-5.4",
        inputTypes: ["text", "image"],
        contextWindow: 272000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 2.5,
        costOutput: 15.0,
      },
      {
        id: "moonshotai/kimi-k2.6",
        name: "Kimi K2.6",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: false,
        costInput: 0.95,
        costOutput: 4.0,
      },
    ],
  },
  {
    key: "cloudflare-ai",
    name: "Cloudflare AI Gateway",
    description: "Cloudflare AI 网关代理",
    icon: "☁️",
    apiType: "openai-chat",
    baseUrl: "https://gateway.ai.cloudflare.com/v1/{accountId}/{gatewayId}",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "claude-opus-4-8",
        name: "Claude Opus 4.8",
        inputTypes: ["text", "image"],
        contextWindow: 1048576,
        maxTokens: 128000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "claude-opus-4-7",
        name: "Claude Opus 4.7",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "claude-sonnet-4-6",
        name: "Claude Sonnet 4.6",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 3.0,
        costOutput: 15.0,
      },
    ],
  },
  {
    key: "cerebras",
    name: "Cerebras",
    description: "Cerebras 超快推理 (Wafer Scale)",
    icon: "🟧",
    apiType: "openai-chat",
    baseUrl: "https://api.cerebras.ai/v1",
    apiKeyPlaceholder: "csk-...",
    requiresApiKey: true,
    models: [
      {
        id: "zai-glm-4.7",
        name: "Z.ai GLM 4.7",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 2.25,
        costOutput: 2.75,
      },
      {
        id: "gpt-oss-120b",
        name: "GPT OSS 120B",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0.35,
        costOutput: 0.75,
      },
      {
        id: "qwen-3-235b-a22b-instruct-2507",
        name: "Qwen 3 235B Instruct",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.6,
        costOutput: 1.2,
      },
      {
        id: "llama3.1-8b",
        name: "Llama 3.1 8B",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.1,
        costOutput: 0.1,
      },
    ],
  },
  {
    key: "deepinfra",
    name: "DeepInfra",
    description: "性价比开源模型推理平台",
    icon: "♾️",
    apiType: "openai-chat",
    baseUrl: "https://api.deepinfra.com/v1/openai",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "deepseek-ai/DeepSeek-V4-Flash",
        name: "DeepSeek V4 Flash",
        inputTypes: ["text"],
        contextWindow: 1048576,
        maxTokens: 1048576,
        reasoning: true,
        costInput: 0.1,
        costOutput: 0.2,
      },
      {
        id: "deepseek-ai/DeepSeek-V3.2",
        name: "DeepSeek V3.2",
        inputTypes: ["text"],
        contextWindow: 163840,
        maxTokens: 163840,
        reasoning: false,
        costInput: 0.26,
        costOutput: 0.38,
      },
      {
        id: "zai-org/GLM-5.1",
        name: "GLM-5.1",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 202752,
        reasoning: true,
        costInput: 1.05,
        costOutput: 3.5,
      },
      {
        id: "stepfun-ai/Step-3.5-Flash",
        name: "Step 3.5 Flash",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: false,
        costInput: 0.1,
        costOutput: 0.3,
      },
      {
        id: "MiniMaxAI/MiniMax-M2.5",
        name: "MiniMax M2.5",
        inputTypes: ["text"],
        contextWindow: 196608,
        maxTokens: 196608,
        reasoning: true,
        costInput: 0.15,
        costOutput: 1.15,
      },
      {
        id: "moonshotai/Kimi-K2.5",
        name: "Kimi K2.5",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: true,
        costInput: 0.45,
        costOutput: 2.25,
      },
      {
        id: "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B",
        name: "NVIDIA Nemotron 3 Super 120B A12B",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: true,
        costInput: 0.1,
        costOutput: 0.5,
      },
      {
        id: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        name: "Llama 3.3 70B Instruct Turbo",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 131072,
        reasoning: false,
        costInput: 0.1,
        costOutput: 0.32,
      },
    ],
  },
  {
    key: "github-copilot",
    name: "GitHub Copilot",
    description: "GitHub Copilot 订阅模型网关，聚合多家旗舰大模型",
    icon: "🐙",
    apiType: "openai-responses",
    baseUrl: "https://api.individual.githubcopilot.com",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "claude-opus-4.8",
        name: "Claude Opus 4.8",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "claude-opus-4.7",
        name: "Claude Opus 4.7",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "claude-opus-4.6",
        name: "Claude Opus 4.6",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "claude-sonnet-4.6",
        name: "Claude Sonnet 4.6",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "gpt-5.5",
        name: "GPT-5.5",
        inputTypes: ["text", "image"],
        contextWindow: 400000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "gpt-5.4",
        name: "GPT-5.4",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "gpt-5.4-mini",
        name: "GPT-5.4 mini",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "gpt-5.4-nano",
        name: "GPT-5.4 nano",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "gpt-5.3-codex",
        name: "GPT-5.3-Codex",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "gemini-3.1-pro",
        name: "Gemini 3.1 Pro",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "gemini-3-flash",
        name: "Gemini 3 Flash",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "gemini-2.5-pro",
        name: "Gemini 2.5 Pro",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "raptor-mini",
        name: "Raptor mini",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "goldeneye",
        name: "Goldeneye",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "gmi",
    name: "GMI Cloud",
    description: "高性能模型推理平台，托管开源与前沿模型",
    icon: "⚡",
    apiType: "openai-chat",
    baseUrl: "https://api.gmi-serving.com/v1",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "openai/gpt-5.4",
        name: "GPT-5.4",
        inputTypes: ["text", "image"],
        contextWindow: 400000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "anthropic/claude-sonnet-4.6",
        name: "Claude Sonnet 4.6",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 64000,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "google/gemini-3.1-flash-lite",
        name: "Gemini 3.1 Flash Lite",
        inputTypes: ["text", "image"],
        contextWindow: 1048576,
        maxTokens: 65536,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "zai-org/GLM-5.1-FP8",
        name: "GLM-5.1 FP8",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "moonshotai/Kimi-K2.5",
        name: "Kimi K2.5",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "deepseek-ai/DeepSeek-V3.2",
        name: "DeepSeek V3.2",
        inputTypes: ["text"],
        contextWindow: 163840,
        maxTokens: 65536,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "novita",
    name: "Novita AI",
    description: "高性能开源模型推理平台，聚合 Kimi、DeepSeek、GLM、Qwen 等主流开源模型",
    icon: "🚀",
    apiType: "openai-chat",
    baseUrl: "https://api.novita.ai/openai/v1",
    apiKeyPlaceholder: "sk_...",
    requiresApiKey: true,
    models: [
      {
        id: "moonshotai/kimi-k2.5",
        name: "Kimi K2.5",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "minimax/minimax-m2.7",
        name: "MiniMax M2.7",
        inputTypes: ["text"],
        contextWindow: 1000000,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "zai-org/glm-5",
        name: "GLM-5",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "deepseek/deepseek-v3-0324",
        name: "DeepSeek V3 0324",
        inputTypes: ["text"],
        contextWindow: 163840,
        maxTokens: 65536,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "deepseek/deepseek-r1-0528",
        name: "DeepSeek R1 0528",
        inputTypes: ["text"],
        contextWindow: 163840,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "qwen/qwen3-235b-a22b-fp8",
        name: "Qwen3 235B A22B FP8",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "opencode",
    name: "OpenCode Zen",
    description: "OpenCode Zen 旗舰模型网关，聚合 Claude、GPT、Gemini、MiniMax 等前沿大模型",
    icon: "🌟",
    apiType: "openai-chat",
    baseUrl: "https://opencode.ai/zen/v1",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "claude-opus-4-8",
        name: "Claude Opus 4.8",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 65536,
        reasoning: true,
        costInput: 5.0,
        costOutput: 25.0,
      },
      {
        id: "gpt-5.5",
        name: "GPT-5.5",
        inputTypes: ["text", "image"],
        contextWindow: 400000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 5.0,
        costOutput: 30.0,
      },
      {
        id: "gemini-3.1-pro",
        name: "Gemini 3.1 Pro",
        inputTypes: ["text", "image"],
        contextWindow: 1048576,
        maxTokens: 65536,
        reasoning: true,
        costInput: 2.0,
        costOutput: 12.0,
      },
      {
        id: "minimax-m2.7",
        name: "MiniMax M2.7",
        inputTypes: ["text"],
        contextWindow: 204800,
        maxTokens: 131072,
        reasoning: true,
        costInput: 0.3,
        costOutput: 1.2,
      },
    ],
  },
  {
    key: "opencode-go",
    name: "OpenCode Zen Go",
    description: "专注编码场景的模型推理网关",
    icon: "🧑‍💻",
    apiType: "openai-chat",
    baseUrl: "https://opencode.ai/zen/go/v1",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        inputTypes: ["text"],
        contextWindow: 1000000,
        maxTokens: 384000,
        reasoning: true,
        costInput: 1.74,
        costOutput: 3.48,
      },
      {
        id: "deepseek-v4-flash",
        name: "DeepSeek V4 Flash",
        inputTypes: ["text"],
        contextWindow: 1000000,
        maxTokens: 384000,
        reasoning: true,
        costInput: 0.14,
        costOutput: 0.28,
      },
    ],
  },
  {
    key: "kilocode",
    name: "KiloCode",
    description: "面向编码场景的 AI 模型网关，自动路由到最优模型",
    icon: "🦘",
    apiType: "openai-chat",
    baseUrl: "https://api.kilo.ai/api/gateway/",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "kilo/auto",
        name: "Kilo Auto",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "cohere",
    name: "Cohere",
    description: "Command 系列模型（OpenAI 兼容端点）",
    icon: "🪢",
    apiType: "openai-chat",
    baseUrl: "https://api.cohere.ai/compatibility/v1",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "command-a-plus-05-2026",
        name: "Command A+",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "north-mini-code-1-0",
        name: "North Mini Code 1.0",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "command-a-reasoning-08-2025",
        name: "Command A Reasoning",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 32000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "command-a-vision-07-2025",
        name: "Command A Vision",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 8000,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "command-a-03-2025",
        name: "Command A",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 8000,
        reasoning: false,
        costInput: 2.5,
        costOutput: 10.0,
      },
    ],
  },
  {
    key: "baseten",
    name: "Baseten",
    description: "高性能开源模型推理平台，托管 GLM、Kimi、DeepSeek、Nemotron 等",
    icon: "🧱",
    apiType: "openai-chat",
    baseUrl: "https://inference.baseten.co/v1",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "deepseek-ai/DeepSeek-V4-Pro",
        name: "DeepSeek V4 Pro",
        inputTypes: ["text"],
        contextWindow: 262000,
        maxTokens: 262000,
        reasoning: true,
        costInput: 1.74,
        costOutput: 3.48,
      },
      {
        id: "moonshotai/Kimi-K2.7-Code",
        name: "Kimi K2.7 Code",
        inputTypes: ["text", "image"],
        contextWindow: 262000,
        maxTokens: 262000,
        reasoning: true,
        costInput: 0.95,
        costOutput: 4.0,
      },
      {
        id: "moonshotai/Kimi-K2.6",
        name: "Kimi K2.6",
        inputTypes: ["text", "image"],
        contextWindow: 262000,
        maxTokens: 262000,
        reasoning: true,
        costInput: 0.95,
        costOutput: 4.0,
      },
      {
        id: "moonshotai/Kimi-K2.5",
        name: "Kimi K2.5",
        inputTypes: ["text", "image"],
        contextWindow: 262000,
        maxTokens: 262000,
        reasoning: true,
        costInput: 0.6,
        costOutput: 3.0,
      },
      {
        id: "zai-org/GLM-5.2",
        name: "GLM 5.2",
        inputTypes: ["text"],
        contextWindow: 202000,
        maxTokens: 202000,
        reasoning: true,
        costInput: 1.4,
        costOutput: 4.4,
      },
      {
        id: "zai-org/GLM-5.1",
        name: "GLM 5.1",
        inputTypes: ["text"],
        contextWindow: 202000,
        maxTokens: 202000,
        reasoning: true,
        costInput: 1.3,
        costOutput: 4.3,
      },
      {
        id: "zai-org/GLM-5",
        name: "GLM 5",
        inputTypes: ["text"],
        contextWindow: 202000,
        maxTokens: 202000,
        reasoning: true,
        costInput: 0.95,
        costOutput: 3.15,
      },
      {
        id: "zai-org/GLM-4.7",
        name: "GLM 4.7",
        inputTypes: ["text"],
        contextWindow: 200000,
        maxTokens: 200000,
        reasoning: true,
        costInput: 0.6,
        costOutput: 2.2,
      },
      {
        id: "thinkingmachines/inkling",
        name: "Inkling",
        inputTypes: ["text", "image"],
        contextWindow: 1048000,
        maxTokens: 32000,
        reasoning: true,
        costInput: 1.0,
        costOutput: 4.05,
      },
      {
        id: "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B",
        name: "Nemotron Ultra",
        inputTypes: ["text"],
        contextWindow: 202000,
        maxTokens: 202000,
        reasoning: true,
        costInput: 0.6,
        costOutput: 2.4,
      },
      {
        id: "nvidia/Nemotron-120B-A12B",
        name: "Nemotron Super",
        inputTypes: ["text"],
        contextWindow: 202000,
        maxTokens: 202000,
        reasoning: true,
        costInput: 0.3,
        costOutput: 0.75,
      },
      {
        id: "openai/gpt-oss-120b",
        name: "GPT OSS 120B",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 0.1,
        costOutput: 0.5,
      },
    ],
  },
  {
    key: "longcat",
    name: "LongCat",
    description: "美团 LongCat 系列模型",
    icon: "🐈",
    apiType: "openai-chat",
    baseUrl: "https://api.longcat.chat/openai",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "LongCat-2.0",
        name: "LongCat 2.0",
        inputTypes: ["text"],
        contextWindow: 1048576,
        maxTokens: 131072,
        reasoning: true,
        costInput: 0.75,
        costOutput: 2.95,
      },
    ],
  },
  {
    key: "meta",
    name: "Meta",
    description: "Meta Muse 系列模型",
    icon: "🔷",
    apiType: "openai-chat",
    baseUrl: "https://api.meta.ai/v1",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "muse-spark-1.1",
        name: "Muse Spark 1.1",
        inputTypes: ["text", "image"],
        contextWindow: 1048576,
        maxTokens: 131072,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "featherless",
    name: "Featherless",
    description: "开源模型无服务器推理",
    icon: "🪶",
    apiType: "openai-chat",
    baseUrl: "https://api.featherless.ai/v1",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "Qwen/Qwen3-32B",
        name: "Qwen3 32B",
        inputTypes: ["text"],
        contextWindow: 32768,
        maxTokens: 4096,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
]
