import type { ProviderTemplate } from "../types"

export const internationalTemplates: ProviderTemplate[] = [
  // ── 国际 Provider ──
  {
    key: "anthropic",
    name: "Anthropic",
    description: "Claude 系列模型",
    icon: "🟤",
    apiType: "anthropic",
    baseUrl: "https://api.anthropic.com",
    apiKeyPlaceholder: "sk-ant-...",
    requiresApiKey: true,
    models: [
      {
        id: "claude-fable-5",
        name: "Claude Fable 5",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 10.0,
        costOutput: 50.0,
      },
      {
        id: "claude-opus-4-8",
        name: "Claude Opus 4.8",
        inputTypes: ["text", "image"],
        contextWindow: 1048576,
        maxTokens: 128000,
        reasoning: true,
        costInput: 15.0,
        costOutput: 75.0,
      },
      {
        id: "claude-opus-4-7",
        name: "Claude Opus 4.7",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 15.0,
        costOutput: 75.0,
      },
      {
        id: "claude-sonnet-4-6",
        name: "Claude Sonnet 4.6",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 3.0,
        costOutput: 15.0,
      },
      {
        id: "claude-opus-4-6",
        name: "Claude Opus 4.6",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 15.0,
        costOutput: 75.0,
      },
      {
        id: "claude-haiku-4-5",
        name: "Claude Haiku 4.5",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 0.8,
        costOutput: 4.0,
      },
    ],
    thinkingStyle: "anthropic",
  },
  {
    key: "anthropic-vertex",
    name: "Anthropic (Vertex AI)",
    description: "Google Cloud Vertex AI 上的 Claude 模型",
    icon: "🔺",
    apiType: "anthropic",
    baseUrl: "https://us-east5-aiplatform.googleapis.com",
    apiKeyPlaceholder: "Google Cloud access token",
    requiresApiKey: true,
    models: [
      {
        id: "claude-fable-5",
        name: "Claude Fable 5",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 10.0,
        costOutput: 50.0,
      },
      {
        id: "claude-opus-4-8",
        name: "Claude Opus 4.8",
        inputTypes: ["text", "image"],
        contextWindow: 1048576,
        maxTokens: 128000,
        reasoning: true,
        costInput: 5.0,
        costOutput: 25.0,
      },
      {
        id: "claude-opus-4-7",
        name: "Claude Opus 4.7",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 5.0,
        costOutput: 25.0,
      },
      {
        id: "claude-sonnet-4-6",
        name: "Claude Sonnet 4.6",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 3.0,
        costOutput: 15.0,
      },
      {
        id: "claude-opus-4-6",
        name: "Claude Opus 4.6",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 5.0,
        costOutput: 25.0,
      },
    ],
    thinkingStyle: "anthropic",
  },
  {
    key: "openai",
    name: "OpenAI",
    description: "GPT 系列模型 (Responses API)",
    icon: "🟢",
    apiType: "openai-responses",
    baseUrl: "https://api.openai.com",
    apiKeyPlaceholder: "sk-...",
    requiresApiKey: true,
    models: [
      {
        id: "gpt-5.6-sol",
        name: "GPT-5.6 Sol",
        inputTypes: ["text", "image"],
        contextWindow: 372000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 5.0,
        costOutput: 30.0,
      },
      {
        id: "gpt-5.6-terra",
        name: "GPT-5.6 Terra",
        inputTypes: ["text", "image"],
        contextWindow: 372000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 2.5,
        costOutput: 15.0,
      },
      {
        id: "gpt-5.6-luna",
        name: "GPT-5.6 Luna",
        inputTypes: ["text", "image"],
        contextWindow: 372000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 1.0,
        costOutput: 6.0,
      },
      {
        id: "gpt-5.5",
        name: "GPT-5.5",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 5.0,
        costOutput: 30.0,
      },
      {
        id: "gpt-5.5-pro",
        name: "GPT-5.5 Pro",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 30.0,
        costOutput: 180.0,
      },
      {
        id: "gpt-5.4",
        name: "GPT-5.4",
        inputTypes: ["text", "image"],
        contextWindow: 272000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 2.5,
        costOutput: 15.0,
      },
      {
        id: "gpt-5.4-pro",
        name: "GPT-5.4 Pro",
        inputTypes: ["text", "image"],
        contextWindow: 1050000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 30.0,
        costOutput: 180.0,
      },
      {
        id: "gpt-5.4-mini",
        name: "GPT-5.4 mini",
        inputTypes: ["text", "image"],
        contextWindow: 400000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 0.75,
        costOutput: 4.5,
      },
      {
        id: "gpt-5.4-nano",
        name: "GPT-5.4 nano",
        inputTypes: ["text", "image"],
        contextWindow: 400000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 0.2,
        costOutput: 1.25,
      },
      {
        id: "gpt-5.3-codex",
        name: "GPT-5.3 Codex",
        inputTypes: ["text", "image"],
        contextWindow: 400000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 1.75,
        costOutput: 14.0,
      },
      {
        id: "gpt-5.3-chat-latest",
        name: "GPT-5.3 Chat (latest)",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 1.75,
        costOutput: 14.0,
      },
      {
        id: "o3-pro",
        name: "GPT o3 Pro",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 20.0,
        costOutput: 80.0,
      },
      {
        id: "o3",
        name: "GPT o3",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 2.0,
        costOutput: 8.0,
      },
      {
        id: "o3-deep-research",
        name: "GPT o3 Deep Research",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 10.0,
        costOutput: 40.0,
      },
      {
        id: "o3-mini",
        name: "GPT o3 Mini",
        inputTypes: ["text"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 1.1,
        costOutput: 4.4,
      },
      {
        id: "o4-mini",
        name: "GPT o4-mini",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 1.1,
        costOutput: 4.4,
      },
      {
        id: "o4-mini-deep-research",
        name: "GPT o4-mini Deep Research",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 2.0,
        costOutput: 8.0,
      },
      {
        id: "o1-pro",
        name: "GPT o1 Pro",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 150.0,
        costOutput: 600.0,
      },
      {
        id: "o1",
        name: "GPT o1",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 15.0,
        costOutput: 60.0,
      },
    ],
  },
  {
    key: "openai-chat",
    name: "OpenAI (Chat)",
    description: "GPT 系列 — Chat Completions API",
    icon: "💬",
    apiType: "openai-chat",
    baseUrl: "https://api.openai.com",
    apiKeyPlaceholder: "sk-...",
    requiresApiKey: true,
    models: [
      {
        id: "gpt-5.6-sol",
        name: "GPT-5.6 Sol",
        inputTypes: ["text", "image"],
        contextWindow: 372000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 5.0,
        costOutput: 30.0,
      },
      {
        id: "gpt-5.6-terra",
        name: "GPT-5.6 Terra",
        inputTypes: ["text", "image"],
        contextWindow: 372000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 2.5,
        costOutput: 15.0,
      },
      {
        id: "gpt-5.6-luna",
        name: "GPT-5.6 Luna",
        inputTypes: ["text", "image"],
        contextWindow: 372000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 1.0,
        costOutput: 6.0,
      },
      {
        id: "gpt-5.5-pro",
        name: "GPT-5.5 Pro",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 30.0,
        costOutput: 180.0,
      },
      {
        id: "gpt-5.5",
        name: "GPT-5.5",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 5.0,
        costOutput: 30.0,
      },
      {
        id: "gpt-5.4-pro",
        name: "GPT-5.4 Pro",
        inputTypes: ["text", "image"],
        contextWindow: 1050000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 30.0,
        costOutput: 180.0,
      },
      {
        id: "gpt-5.4",
        name: "GPT-5.4",
        inputTypes: ["text", "image"],
        contextWindow: 272000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 2.5,
        costOutput: 15.0,
      },
      {
        id: "gpt-5.4-mini",
        name: "GPT-5.4 mini",
        inputTypes: ["text", "image"],
        contextWindow: 400000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 0.75,
        costOutput: 4.5,
      },
      {
        id: "gpt-5.4-nano",
        name: "GPT-5.4 nano",
        inputTypes: ["text", "image"],
        contextWindow: 400000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 0.2,
        costOutput: 1.25,
      },
      {
        id: "gpt-5.3-codex",
        name: "GPT-5.3 Codex",
        inputTypes: ["text", "image"],
        contextWindow: 400000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 1.75,
        costOutput: 14.0,
      },
      {
        id: "gpt-5.3-chat-latest",
        name: "GPT-5.3 Chat (latest)",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 1.75,
        costOutput: 14.0,
      },
      {
        id: "o3-pro",
        name: "GPT o3 Pro",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 20.0,
        costOutput: 80.0,
      },
      {
        id: "o3",
        name: "GPT o3",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 2.0,
        costOutput: 8.0,
      },
      {
        id: "o3-deep-research",
        name: "GPT o3 Deep Research",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 10.0,
        costOutput: 40.0,
      },
      {
        id: "o3-mini",
        name: "GPT o3 Mini",
        inputTypes: ["text"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 1.1,
        costOutput: 4.4,
      },
      {
        id: "o4-mini",
        name: "GPT o4-mini",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 1.1,
        costOutput: 4.4,
      },
      {
        id: "o4-mini-deep-research",
        name: "GPT o4-mini Deep Research",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 2.0,
        costOutput: 8.0,
      },
      {
        id: "o1-pro",
        name: "GPT o1 Pro",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 150.0,
        costOutput: 600.0,
      },
      {
        id: "o1",
        name: "GPT o1",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 15.0,
        costOutput: 60.0,
      },
    ],
  },
  {
    key: "deepseek",
    name: "DeepSeek",
    description: "DeepSeek 系列推理模型",
    icon: "🔵",
    apiType: "openai-chat",
    baseUrl: "https://api.deepseek.com",
    apiKeyPlaceholder: "sk-...",
    requiresApiKey: true,
    models: [
      {
        id: "deepseek-v4-flash",
        name: "DeepSeek V4 Flash",
        inputTypes: ["text"],
        contextWindow: 1000000,
        maxTokens: 384000,
        reasoning: true,
        costInput: 0.14,
        costOutput: 0.28,
      },
      {
        id: "deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        inputTypes: ["text"],
        contextWindow: 1000000,
        maxTokens: 384000,
        reasoning: true,
        costInput: 1.74,
        costOutput: 3.48,
      },
      {
        id: "deepseek-chat",
        name: "DeepSeek Chat (V3)",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.28,
        costOutput: 0.42,
      },
      {
        id: "deepseek-reasoner",
        name: "DeepSeek Reasoner (R1)",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.28,
        costOutput: 0.42,
      },
    ],
  },
  {
    key: "google-gemini",
    name: "Google Gemini",
    description: "Gemini 系列多模态模型",
    icon: "💎",
    apiType: "openai-chat",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    apiKeyPlaceholder: "AIza...",
    requiresApiKey: true,
    models: [
      {
        id: "gemini-3.5-flash",
        name: "Gemini 3.5 Flash",
        inputTypes: ["text", "image"],
        contextWindow: 1048576,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "gemini-3.1-pro-preview",
        name: "Gemini 3.1 Pro Preview",
        inputTypes: ["text", "image", "video"],
        contextWindow: 1048576,
        maxTokens: 65536,
        reasoning: true,
        costInput: 1.25,
        costOutput: 10.0,
      },
      {
        id: "gemini-3.1-flash-lite",
        name: "Gemini 3.1 Flash Lite",
        inputTypes: ["text", "image"],
        contextWindow: 1048576,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "gemini-3-flash-preview",
        name: "Gemini 3 Flash Preview",
        inputTypes: ["text", "image", "video"],
        contextWindow: 1048576,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.15,
        costOutput: 0.6,
      },
      {
        id: "gemini-2.5-pro",
        name: "Gemini 2.5 Pro",
        inputTypes: ["text", "image", "video"],
        contextWindow: 1048576,
        maxTokens: 65536,
        reasoning: true,
        costInput: 1.25,
        costOutput: 10.0,
      },
      {
        id: "gemini-2.5-flash",
        name: "Gemini 2.5 Flash",
        inputTypes: ["text", "image", "video"],
        contextWindow: 1048576,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.15,
        costOutput: 0.6,
      },
      {
        id: "gemini-2.5-flash-lite",
        name: "Gemini 2.5 Flash-Lite",
        inputTypes: ["text", "image"],
        contextWindow: 1048576,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.1,
        costOutput: 0.4,
      },
    ],
  },
  {
    key: "xai",
    name: "xAI",
    description: "Grok 系列模型",
    icon: "✖️",
    apiType: "openai-chat",
    baseUrl: "https://api.x.ai/v1",
    apiKeyPlaceholder: "xai-...",
    requiresApiKey: true,
    models: [
      {
        id: "grok-4.3",
        name: "Grok 4.3",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 1.25,
        costOutput: 2.5,
      },
      {
        id: "grok-4.20-beta-latest-reasoning",
        name: "Grok 4.20 Beta Latest (Reasoning)",
        inputTypes: ["text", "image"],
        contextWindow: 2000000,
        maxTokens: 30000,
        reasoning: true,
        costInput: 1.25,
        costOutput: 2.5,
      },
      {
        id: "grok-4.20-beta-latest-non-reasoning",
        name: "Grok 4.20 Beta Latest (Non-Reasoning)",
        inputTypes: ["text", "image"],
        contextWindow: 2000000,
        maxTokens: 30000,
        reasoning: false,
        costInput: 1.25,
        costOutput: 2.5,
      },
      {
        id: "grok-4-1-fast",
        name: "Grok 4.1 Fast",
        inputTypes: ["text", "image"],
        contextWindow: 2000000,
        maxTokens: 30000,
        reasoning: true,
        costInput: 0.2,
        costOutput: 0.5,
      },
      {
        id: "grok-4-1-fast-non-reasoning",
        name: "Grok 4.1 Fast (Non-Reasoning)",
        inputTypes: ["text", "image"],
        contextWindow: 2000000,
        maxTokens: 30000,
        reasoning: false,
        costInput: 0.2,
        costOutput: 0.5,
      },
      {
        id: "grok-4-fast",
        name: "Grok 4 Fast",
        inputTypes: ["text", "image"],
        contextWindow: 2000000,
        maxTokens: 30000,
        reasoning: true,
        costInput: 0.2,
        costOutput: 0.5,
      },
      {
        id: "grok-4-fast-non-reasoning",
        name: "Grok 4 Fast (Non-Reasoning)",
        inputTypes: ["text", "image"],
        contextWindow: 2000000,
        maxTokens: 30000,
        reasoning: false,
        costInput: 0.2,
        costOutput: 0.5,
      },
      {
        id: "grok-4",
        name: "Grok 4",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 3.0,
        costOutput: 15.0,
      },
      {
        id: "grok-4-0709",
        name: "Grok 4 0709",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 64000,
        reasoning: false,
        costInput: 3.0,
        costOutput: 15.0,
      },
      {
        id: "grok-build-0.1",
        name: "Grok Build 0.1",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 1.0,
        costOutput: 2.0,
      },
      {
        id: "grok-3",
        name: "Grok 3",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 3.0,
        costOutput: 15.0,
      },
      {
        id: "grok-3-fast",
        name: "Grok 3 Fast",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 5.0,
        costOutput: 25.0,
      },
      {
        id: "grok-3-mini",
        name: "Grok 3 Mini",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0.3,
        costOutput: 0.5,
      },
      {
        id: "grok-3-mini-fast",
        name: "Grok 3 Mini Fast",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0.6,
        costOutput: 4.0,
      },
      {
        id: "grok-code-fast-1",
        name: "Grok Code Fast 1",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 10000,
        reasoning: true,
        costInput: 0.2,
        costOutput: 1.5,
      },
    ],
  },
  {
    key: "mistral",
    name: "Mistral",
    description: "Mistral 系列欧洲模型",
    icon: "🟣",
    apiType: "openai-chat",
    baseUrl: "https://api.mistral.ai/v1",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "mistral-medium-3-5",
        name: "Mistral Medium 3.5",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 8192,
        reasoning: true,
        costInput: 1.5,
        costOutput: 7.5,
      },
      {
        id: "mistral-large-latest",
        name: "Mistral Large",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0.5,
        costOutput: 1.5,
      },
      {
        id: "mistral-medium-2508",
        name: "Mistral Medium 3.1",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.4,
        costOutput: 2.0,
      },
      {
        id: "mistral-small-latest",
        name: "Mistral Small",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: true,
        costInput: 0.1,
        costOutput: 0.3,
      },
      {
        id: "magistral-small",
        name: "Magistral Small",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 40000,
        reasoning: true,
        costInput: 0.5,
        costOutput: 1.5,
      },
      {
        id: "devstral-medium-latest",
        name: "Devstral 2",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0.4,
        costOutput: 2.0,
      },
      {
        id: "codestral-latest",
        name: "Codestral",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0.3,
        costOutput: 0.9,
      },
      {
        id: "pixtral-large-latest",
        name: "Pixtral Large",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 32768,
        reasoning: false,
        costInput: 2.0,
        costOutput: 6.0,
      },
    ],
  },
]
