import type { ProviderTemplate } from "../types"

export const localTemplates: ProviderTemplate[] = [
  // ── 本地 / 自托管 Provider ──
  {
    key: "litellm",
    name: "LiteLLM",
    description: "统一 LLM API 代理网关",
    icon: "🔗",
    apiType: "openai-chat",
    baseUrl: "http://127.0.0.1:4000",
    apiKeyPlaceholder: "...",
    requiresApiKey: false,
    models: [
      {
        id: "your-model-id",
        name: "Your Model",
        inputTypes: [],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "ollama",
    name: "Ollama",
    description: "本地 + 云端模型推理，无需 API Key",
    icon: "🦙",
    apiType: "openai-chat",
    baseUrl: "http://127.0.0.1:11434",
    apiKeyPlaceholder: "（无需填写）",
    requiresApiKey: false,
    models: [
      {
        id: "glm-4.7-flash",
        name: "GLM 4.7 Flash",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "qwen3:32b",
        name: "Qwen 3 32B",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "kimi-k2.5:cloud",
        name: "Kimi K2.5 (云端)",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "minimax-m2.5:cloud",
        name: "MiniMax M2.5 (云端)",
        inputTypes: ["text"],
        contextWindow: 200000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "glm-5:cloud",
        name: "GLM-5 (云端)",
        inputTypes: ["text"],
        contextWindow: 204800,
        maxTokens: 131072,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "vllm",
    name: "vLLM",
    description: "高性能本地推理引擎",
    icon: "⚙️",
    apiType: "openai-chat",
    baseUrl: "http://127.0.0.1:8000",
    apiKeyPlaceholder: "（无需填写）",
    requiresApiKey: false,
    models: [
      {
        id: "your-model-id",
        name: "Your Model",
        inputTypes: [],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "lm-studio",
    name: "LM Studio",
    description: "桌面端本地模型推理",
    icon: "🖥️",
    apiType: "openai-chat",
    baseUrl: "http://127.0.0.1:1234",
    apiKeyPlaceholder: "（无需填写）",
    requiresApiKey: false,
    models: [
      {
        id: "your-model-id",
        name: "Your Model",
        inputTypes: [],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "sglang",
    name: "SGLang",
    description: "高性能本地推理引擎",
    icon: "⚡",
    apiType: "openai-chat",
    baseUrl: "http://127.0.0.1:30000",
    apiKeyPlaceholder: "（无需填写）",
    requiresApiKey: false,
    models: [
      {
        id: "your-model-id",
        name: "Your Model",
        inputTypes: [],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
]
