//! Builds the embedded Web GUI bundle from the Vite `dist/` output.
//!
//! Two jobs:
//!
//! 1. Fill in a placeholder `index.html` when `dist/` is empty, so a fresh
//!    clone without a prior `pnpm build` still produces a working binary.
//! 2. In release builds, brotli-compress every asset and emit a single blob
//!    plus an index for [`crate::web_assets`] to serve. Storing the bytes
//!    compressed is what keeps them small *in the binary* — the server hands
//!    them straight to the browser with `Content-Encoding: br`.
//!
//! Debug builds skip step 2 and serve `dist/` from disk instead: brotli at
//! quality 11 over the whole bundle costs minutes, which would make every
//! front-end change unbearable during development.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

const PLACEHOLDER_INDEX_HTML: &str = r#"<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Hope Agent — Front-end not built</title>
  <link rel="stylesheet" href="/placeholder.css" />
</head>
<body>
  <main>
    <h1>Hope Agent is running</h1>
    <p>
      The Web GUI has not been built yet. Run
      <code>pnpm build</code> in the project root and restart
      <code>hope-agent server</code> to load the real interface.
    </p>
    <p>The backend API remains fully functional at <code>/api/*</code>.</p>
  </main>
</body>
</html>
"#;

const PLACEHOLDER_CSS: &str = r#"html,body{margin:0;padding:0;font-family:system-ui,-apple-system,sans-serif;
background:#0b0d11;color:#e6e6e6;min-height:100vh;display:flex;
align-items:center;justify-content:center}
main{max-width:560px;padding:2rem;border:1px solid #2a2d33;border-radius:12px;background:#14171c}
h1{font-size:1.6rem;margin:0 0 1rem 0}
p{line-height:1.6;margin:0 0 1rem 0}
code{background:#1f232a;padding:.15rem .35rem;border-radius:4px;font-size:.9em}"#;

/// Brotli quality. 11 is the maximum and roughly 4:1 on minified JS; it is
/// slow to compress and just as fast as gzip to decompress, which is the right
/// trade for something compressed once in CI and decompressed on every client.
const BROTLI_QUALITY: i32 = 11;
/// Window size (2^22 = 4 MiB). Large enough to catch the long-range repetition
/// in multi-megabyte JS chunks that a gzip-sized 32 KiB window misses.
const BROTLI_WINDOW: i32 = 22;

/// Keep the raw bytes when compression barely helps (already-compressed png /
/// woff2), so we neither waste build time nor pay a pointless decompress.
const MIN_COMPRESSION_GAIN: f64 = 0.95;

fn main() {
    // Resolve ../../dist relative to this crate. Read CARGO_MANIFEST_DIR at RUN
    // time, not with `env!`: that bakes the path in when the build script is
    // compiled, and a shared CARGO_TARGET_DIR reuses one compiled build script
    // across every worktree — so the placeholder lands in whichever worktree
    // compiled it first (even a deleted one).
    let manifest = match std::env::var("CARGO_MANIFEST_DIR") {
        Ok(dir) => PathBuf::from(dir),
        Err(e) => {
            println!("cargo:warning=ha-server build.rs: CARGO_MANIFEST_DIR unavailable: {e}");
            return;
        }
    };
    let dist = manifest.join("..").join("..").join("dist");

    if let Err(e) = fs::create_dir_all(&dist) {
        println!(
            "cargo:warning=ha-server build.rs: failed to create {}: {}",
            dist.display(),
            e
        );
        return;
    }

    ensure_placeholder(&dist);

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let embed = std::env::var("PROFILE").as_deref() != Ok("debug");

    let mut files = Vec::new();
    collect_files(&dist, &dist, &mut files);
    files.sort_by(|a, b| a.0.cmp(&b.0));

    // Watch each file individually. A `rerun-if-changed` on the directory only
    // tracks that directory's own mtime, so a `pnpm build` that rewrites files
    // in place leaves a stale front-end baked into the binary.
    println!("cargo:rerun-if-changed={}", dist.display());
    for (_, abs) in &files {
        println!("cargo:rerun-if-changed={}", abs.display());
    }

    let entries = if embed {
        write_bundle(&out_dir, &files)
    } else {
        // Debug: emit an empty index; web_assets falls back to reading `dist/`
        // from disk so front-end edits show up without recompiling.
        fs::write(out_dir.join("frontend_assets.bin"), []).expect("write empty asset blob");
        Vec::new()
    };

    let mut src = String::new();
    src.push_str(
        "// @generated by build.rs — do not edit.\n\
         pub static ASSET_BLOB: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/frontend_assets.bin\"));\n\
         /// (path, offset, stored_len, raw_len). `stored_len == raw_len` means the\n\
         /// bytes are stored uncompressed. Sorted by path for binary search.\n\
         pub static ASSET_INDEX: &[(&str, u32, u32, u32)] = &[\n",
    );
    for (path, offset, stored, raw) in &entries {
        src.push_str(&format!(
            "    ({:?}, {}, {}, {}),\n",
            path, offset, stored, raw
        ));
    }
    src.push_str("];\n");
    src.push_str(&format!(
        "/// Absolute `dist/` path, used by debug builds to serve from disk.\n\
         pub const DIST_DIR: &str = {:?};\n",
        dist.display().to_string()
    ));
    fs::write(out_dir.join("frontend_assets.rs"), src).expect("write asset index");
}

fn ensure_placeholder(dist: &Path) {
    let index = dist.join("index.html");
    if !index.exists() {
        if let Err(e) = fs::write(&index, PLACEHOLDER_INDEX_HTML) {
            println!(
                "cargo:warning=ha-server build.rs: failed to write placeholder index.html: {e}"
            );
        }
    }
    let css = dist.join("placeholder.css");
    if !css.exists() {
        if let Err(e) = fs::write(&css, PLACEHOLDER_CSS) {
            println!("cargo:warning=ha-server build.rs: failed to write placeholder.css: {e}");
        }
    }
}

/// Collect `(relative_slash_path, absolute_path)` for every file under `root`.
fn collect_files(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(e) => {
            println!(
                "cargo:warning=ha-server build.rs: cannot read {}: {e}",
                dir.display()
            );
            return;
        }
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_files(root, &path, out);
        } else if path.is_file() {
            if let Ok(rel) = path.strip_prefix(root) {
                let rel = rel
                    .components()
                    .map(|c| c.as_os_str().to_string_lossy().into_owned())
                    .collect::<Vec<_>>()
                    .join("/");
                out.push((rel, path));
            }
        }
    }
}

/// Compress every asset into one concatenated blob. Returns the index entries.
fn write_bundle(out_dir: &Path, files: &[(String, PathBuf)]) -> Vec<(String, u32, u32, u32)> {
    let threads = std::thread::available_parallelism()
        .map(|n| n.get())
        .unwrap_or(4);

    // Compress in parallel — quality 11 over a ~30 MB bundle is minutes of CPU,
    // and it is embarrassingly parallel across files.
    let compressed: Vec<(String, Vec<u8>, usize)> = std::thread::scope(|scope| {
        let chunk = files.len().div_ceil(threads.max(1)).max(1);
        let handles: Vec<_> = files
            .chunks(chunk)
            .map(|slice| scope.spawn(move || slice.iter().map(compress_one).collect::<Vec<_>>()))
            .collect();
        handles
            .into_iter()
            .flat_map(|h| h.join().expect("compression thread panicked"))
            .collect()
    });

    let mut blob: Vec<u8> = Vec::new();
    let mut entries = Vec::with_capacity(compressed.len());
    for (path, bytes, raw_len) in compressed {
        let offset = blob.len() as u32;
        let stored = bytes.len() as u32;
        blob.extend_from_slice(&bytes);
        entries.push((path, offset, stored, raw_len as u32));
    }

    let mut f = fs::File::create(out_dir.join("frontend_assets.bin")).expect("create asset blob");
    f.write_all(&blob).expect("write asset blob");

    entries
}

fn compress_one((rel, abs): &(String, PathBuf)) -> (String, Vec<u8>, usize) {
    let raw = fs::read(abs).unwrap_or_default();
    let raw_len = raw.len();

    let params = brotli::enc::BrotliEncoderParams {
        quality: BROTLI_QUALITY,
        lgwin: BROTLI_WINDOW,
        ..Default::default()
    };

    let mut out = Vec::new();
    let ok = brotli::BrotliCompress(&mut raw.as_slice(), &mut out, &params).is_ok();

    // Store raw when compression fails or barely pays — the index marks this
    // with `stored_len == raw_len`.
    if !ok || out.len() as f64 >= raw_len as f64 * MIN_COMPRESSION_GAIN {
        return (rel.clone(), raw, raw_len);
    }
    (rel.clone(), out, raw_len)
}
